### ISSUE TITLE
InvalidAudienceError results in 500 Error Rather than 401/403

### ISSUE THREAD

**Issue by cancan101** [GetBlimp/django-rest-framework-jwt#100]
Right now just `ExpiredSignature` and `DecodeError` are caught. ([See here](https://github.com/GetBlimp/django-rest-framework-jwt/blob/cb8fab26009767e4b85a882f9f6a169318c8114e/rest_framework_jwt/authentication.py#L31)) but  `InvalidAudienceError` extends `InvalidTokenError`.

`InvalidAudienceError` should be caught and then either return `None` or raise a 401 or 403.

**Comment by jpadilla** [comment]
@cancan101 decided for now to catch `InvalidTokenError` and raise `AuthenticationFailed`.

**Comment by jpadilla** [comment]
Fixed in v1.5.0
