### ISSUE TITLE
FieldError when using custom user model

### ISSUE THREAD

**Issue by karmux** [GetBlimp/django-rest-framework-jwt#102]
Django docs suggest to inherit custom user model from AbstractBaseUser class:
https://docs.djangoproject.com/en/1.8/topics/auth/customizing/#specifying-a-custom-user-model

AbstractBaseUser has an attribute "is_active" that is True by default (it's not a database field)
https://github.com/django/django/blob/master/django/contrib/auth/models.py#L199

In this case django-rest-framework-jwt throws an error "FieldError: Cannot resolve keyword 'is_active' into field." when trying to do authentication:
https://github.com/GetBlimp/django-rest-framework-jwt/blob/deea4ad14dfd4611fb19ad3cab133b8dd3e8959c/rest_framework_jwt/authentication.py#L55

Also token verifycation and refresh fail:
https://github.com/GetBlimp/django-rest-framework-jwt/blob/faa772c53efe7123776206fa0513d597c5e2c368/rest_framework_jwt/serializers.py#L115

**Comment by jpadilla** [comment]
Fixed here 48b2c086d71d485b75f100a83179324b7feb1ece. Checked for `user.is_active` instead of querying for it.

**Comment by timmy2702** [comment]
Had the same problem and your fixes worked well!

**Comment by jpadilla** [comment]
@timmy2702 great to hear!

**Comment by ianveshi** [comment]
May I know when will a new package be released with this fix?

**Comment by jpadilla** [comment]
@ianveshi We'll look into try to do so this week.

**Comment by ianveshi** [comment]
@jpadilla Thanks.
