### ISSUE TITLE
verify_expiration no longer supported by pyJWT

### ISSUE THREAD

**Issue by cancan101** [GetBlimp/django-rest-framework-jwt#103]
This line likely needs to be changed: https://github.com/GetBlimp/django-rest-framework-jwt/blob/96eb5d9838967a88dfc7d92acfd21ba7481bf50b/rest_framework_jwt/utils.py#L54

perhaps `options={'verify_exp': XXX}` should be used.

see: https://github.com/jpadilla/pyjwt/issues/147

**Comment by lucacorti** [comment]
I'm running into issues with `JWT_VERIFY_EXPIRATION` set to `False`, basically it seems to have no effect at all. I guess it depends on this.

**Comment by jpadilla** [comment]
Checking this out right now

**Comment by lucacorti** [comment]
Downgrading to PyJWT 1.0.1 seems to work until a new version of django-rest-framework-jwt and/or PyJWT is issued.
