### ISSUE TITLE
Should getting a token require POST?

### ISSUE THREAD

**Issue by AlexHill** [GetBlimp/django-rest-framework-jwt#104]
This is mostly academic, but retrieving a JWT token has no side-effects on the server, so I reckon it should be possible with a GET request. Thoughts?

**Comment by jpadilla** [comment]
Don't see why it should be anything else, the client doesn't really know what should be going on the server. This is aligned with DRF's own token endpoint.

Also, a common argument is that you should not put sensitive information in a query string as web servers usually log the request URL.
