### ISSUE TITLE
ObtainJSONWebToken post method should return 401 status code for invalid credentials

### ISSUE THREAD

**Issue by parthshah** [GetBlimp/django-rest-framework-jwt#107]
JSONWebTokenSerailizer:validate() should raise exception.AuthenticationFailed exception instead of serializer.ValidationError exception when authenticate() fails.

**Comment by jpadilla** [comment]
I disagree that it should be a `401` error. 

> The request requires user authentication. The response MUST include a WWW-Authenticate header field (section 14.47) containing a challenge applicable to the requested resource.

This endpoint can't and doesn't require authentication, but only returns if valid credentials were given.

**Comment by parthshah** [comment]
Makes sense, thanks for the explanation.
