### ISSUE TITLE
Enable expiration by user

### ISSUE THREAD

**Issue by LiteWait** [GetBlimp/django-rest-framework-jwt#125]
I don't if this is possible, but I wonder if we could have a flag or something to not expire certain users and allow them to manual refresh.  We've got internal apps that run from other server we want to authenticate once and then never expire.  Any guidance would be appreciated.  Thanks.

**Comment by jpadilla** [comment]
@LiteWait that's a valid use case for sure, but very implementation specific. Don't us doing this in this package any time soon.
