### ISSUE TITLE
Add BrowsableAPIRenderer to views?

### ISSUE THREAD

**Issue by mcgeeco** [GetBlimp/django-rest-framework-jwt#126]
Hi, loving the package. Sorry if this is a silly question, but is there a reason the browsable api renderer is left off of the views? I find it very handy when working and testing, and I know the front-end guys definitely do as well. Easy enough to add it myself, but was just wondering if it's worth considering adding it to the code. Thanks!

**Comment by jpadilla** [comment]
@mcgeeco 0357c36fffc7243dd87a0f257903a79215a4f252 should take care of this and just use whatever you've set as your defaults. If that works for you I'll go ahead and release a new version with this today.

**Comment by mcgeeco** [comment]
Oh, that's a much better idea. Thanks!

**Comment by jpadilla** [comment]
https://github.com/GetBlimp/django-rest-framework-jwt/releases/tag/1.6.0
