### ISSUE TITLE
Method utils.jwt_payload_handler ignores USERNAME_FIELD

### ISSUE THREAD

**Issue by rm--** [GetBlimp/django-rest-framework-jwt#128]
I have seen with #18 the `serializers.py` got an username access with paying attention to `USERNAME_FIELD`. But in `utils.jwt_payload_handler` it is still missing. (;

In my option there should be an implementation like in [django-compat](https://github.com/arteria/django-compat/blob/master/compat/__init__.py#L158-177), also for compatibility reasons.

**Comment by erichonkanen** [comment]
@rm-- I agree the django-compat snippet looks good, could you submit a PR with the changes?

**Comment by rm--** [comment]
@erichonkanen Of course. Give my some days.

**Comment by rm--** [comment]
thanks!
