### ISSUE TITLE
Implement password reset mechanisim

### ISSUE THREAD

**Issue by norbertpy** [GetBlimp/django-rest-framework-jwt#130]
How can I use DRF JWT to implement password reset? Is it possible to generate such token only for email address value so I can email a link and verify the token later on?

**Comment by mcgeeco** [comment]
I could be wrong, but I don't think this project is planning to include endpoints like that. Your best bet is to write your own, or do what I did and combine this package with something like [Djoser](https://github.com/sunscrapers/djoser).

**Comment by erichonkanen** [comment]
@norbertpy I think that is outside the scope of this package but there are plenty of examples online such as:

https://docs.djangoproject.com/en/1.8/topics/auth/default/#changing-passwords
https://github.com/brutasse/django-password-reset
http://ruddra.com/blog/2014/10/21/make-own-forgot-slash-reset-password-in-django/

(from quick google search)
