### ISSUE TITLE
Get token if email confirmed

### ISSUE THREAD

**Issue by mhipo1364** [GetBlimp/django-rest-framework-jwt#131]
Hi guys,

I have a situation, I'm using django-allauth, and my user will active if he confirmed his email.

Till here everything is fine, but jwt will generate token if my user not confirmed by email

How can I fix this?

**Comment by jpadilla** [comment]
@mhipo1364 You'll need too look at providing a custom authentication class based on `JSONWebTokenAuthentication` overwriting the following https://github.com/GetBlimp/django-rest-framework-jwt/blob/master/rest_framework_jwt/authentication.py#L45

**Comment by mhipo1364** [comment]
@jpadilla Really thanks :+1:
