### ISSUE TITLE
Docs do not mention imports

### ISSUE THREAD

**Issue by Miserlou** [GetBlimp/django-rest-framework-jwt#132]
Just started using DRF-JWT, and I'm a bit of a bug hunter, so expect a few bugs from me in the near future. :)

First one is that the docs don't mention any imports of rest_framework_jwt anywhere. What needs to be imported? There is also no mention of adding 'rest_framework_jwt' to INSTALLED_APPS. These kinds of things are obvious if you use a package alot, but if you're following a long with a set up guide for the first time, it's annoying when you perfectly follow instructions but they don't work because of stuff like this.

**Comment by jpadilla** [comment]
@Miserlou this package has no need to be added to `INSTALLED_APPS` because it doesn't provide any models, templatetags, etc.

The [usage](https://getblimp.github.io/django-rest-framework-jwt/#usage) section shows the only imports that would be needed to get started.
