### ISSUE TITLE
error: orig_iat field is required

### ISSUE THREAD

**Issue by carlware** [GetBlimp/django-rest-framework-jwt#134]
I getting this error ```orig_iat field is required``` while I try to refresh the token. Checking the code the error comes from the serializer [orig_iat](https://github.com/GetBlimp/django-rest-framework-jwt/blob/5cdc62cb817149ff5fb57b6a19a6980b98d0dba7/rest_framework_jwt/serializers.py#L149).

Decoding the payload I noticed the this field is not in the dictionary. The only fields in the dictionary are username, user_id, email and exp. The JWT_ALLOW_REFRESH is set to True.

**Comment by carlware** [comment]
Ooops, I didn't notice that this was added recently and is only in the master. The version 1.6.0 does not support this option yet.

**Comment by thedarklord1** [comment]
Hey @carlware I am also getting the same error while posting the token refresh request. Could you please help me with how to resolve that error? I have installed the rest-framework-jwt using pip.

**Comment by carlware** [comment]
In my case, I was using the version 1.6.0 which does not include the ```orig_iat``` [v1.6.0](https://github.com/GetBlimp/django-rest-framework-jwt/blob/1.6.0/rest_framework_jwt/utils.py#L19-L30). After update to the most recent version with the command ```pip install -U djangorestframework-jwt```, this version include in the token the ```orig_iat```. Also notice that you have to allow refresh by default is false.
My settings looks like:
```
JWT_AUTH = {
    'JWT_EXPIRATION_DELTA': datetime.timedelta(hours=1),
    'JWT_ALLOW_REFRESH': True,
}
```
I hope, this can help you.

**Comment by thedarklord1** [comment]
Thanks a lot @carlware 
It worked after setting JWT_ALLOW_REFRESH to True.
