### ISSUE TITLE
Throttling

### ISSUE THREAD

**Issue by resalisbury** [GetBlimp/django-rest-framework-jwt#135]
Since `JSONWebTokenAPIView` sets `throttle_classes = ()`, a global throttle won't actually apply to views that inherit from `JSONWebTokenAPIView`.  Wouldn't it be better to leave `throttle_classes = api_settings.DEFAULT_THROTTLE_CLASSES` as in the `APIView` it inherits from?

**Comment by jpadilla** [comment]
@resalisbury a PR removing it would be great :)

**Comment by resalisbury** [comment]
Perfect, I'll put one in!

**Comment by jpadilla** [comment]
Closed via #138
