### ISSUE TITLE
Add support for using public/private keys

### ISSUE THREAD

**Issue by orf** [GetBlimp/django-rest-framework-jwt#136]
The default JWT_DECODE_HANDLER/JWT_ENCODE_HANDLER blindly use the JWT_SECRET_KEY. However, and quite annoyingly, if you are using public/private keys to handle the verification then you need to pass the private key in the encode_handler, and the public one in the decode_handler.

The quickest way to fix this is to modify jwt_decode_handler like so:

```
def jwt_decode_handler(token):
    options = {
        'verify_exp': api_settings.JWT_VERIFY_EXPIRATION,
    }

    key = api_settings.JWT_SECRET_KEY
    if hasattr(key, "public_key"):
        key = key.public_key()

    return jwt.decode(
        token,
        key...
```

But obviously that's not super clean, although I think it's somewhat elegant and does fix the issue. Any thoughts?

**Comment by soichih** [comment]
+1 

I also need to specify separate public / private keys to be used for RSA algorithm.

I think using additional configs (instead of JWT_SECRET_KEY) might be a bit cleaner.. 

Like..
```
'JWT_PUBLIC_KEY': open('/path/to/public.pem').read(),
'JWT_PRIVATE_KEY': open('/path/to/private.pem').read(),
```

pyjwt accepts both PEM and SSH object (like you are doing?) so either format can be passed from the config.

Then, we can do something like ...

```
def jwt_decode_handler(token):
    options = {
        'verify_exp': api_settings.JWT_VERIFY_EXPIRATION,
    }

    key = api_settings.JWT_SECRET_KEY
    if hasattr(api_settings, 'JWT_PUBLIC_KEY'):
        key = api_settings.JWT_PUBLIC_KEY

    return jwt.decode(
        token,
        key,
        api_settings.JWT_VERIFY,
        options=options,
        leeway=api_settings.JWT_LEEWAY,
        audience=api_settings.JWT_AUDIENCE,
        issuer=api_settings.JWT_ISSUER,
        algorithms=[api_settings.JWT_ALGORITHM]
    )

```

I am not sure
