### ISSUE TITLE
`NotImplementedError` on accessing `request.DATA`

### ISSUE THREAD

**Issue by cgroner** [GetBlimp/django-rest-framework-jwt#139]
From `django-rest-framework` v3.2, any attempts to access `request.DATA` will raise a `NotImplementedError` with the following message:

> `request.DATA` has been deprecated in favor of `request.data` since version 3.0, and has been fully removed as of version 3.2.

You can see the change [commit here](https://github.com/tomchristie/django-rest-framework/commit/f7d44dfae0d73a33373f62cf1905c10f89fcfb9e). The error originates [here in `views.py`](https://github.com/cgroner/django-rest-framework-jwt/blob/master/rest_framework_jwt/views.py#L56).

Note that the `request.data` property appears to have been added in `django-rest-framework` v3, so simply changing `request.DATA` to `request.data` may make this package incompatible with earlier versions.

**Comment by tomchristie** [comment]
Probably need a compat wrapper to support both 2.x and 3.x

**Comment by cgroner** [comment]
Looks like there's a pull request that addresses this. #140

**Comment by stunaz** [comment]
This a blocker for django-rest-framework v3.2

**Comment by sikko** [comment]
+1

**Comment by frlinw** [comment]
+1

**Comment by tomchristie** [comment]
@sikko @frlinw I understand that folks are keen to get this in, but it's bad form to "+1" on an issue.
Most likely this'll get sorted shortly, work around in the meantime or stick with 3.1.x for a few more days :smile:

**Comment by frlinw** [comment]
it's because I love you and your work, this +1 is a gift for you !
I'm waiting for the patch but find/replace worked fine ;)

**Comment by tomchristie** [comment]
:p

**Comment by jpadilla** [comment]
Closed via 6d8614268d60f894dad026b5603c8a2fefc35e2f.

**Comment by holms** [comment]
Is this fix on pypi? I still have this issue. Version is 3.2.2

**Comment by stunaz** [comment]
it should be fixed with django-rest-framework-jwt v1.7.1

**Comment by ukjin1192** [comment]
Just one minor thing. Setting `contentType: false` in ajax could also yield this error.

**Comment by rohitranjan1991** [comment]
I am using v1.7.2 and am still facing this issue. Any workarounds ?

**Comment by stunaz** [comment]
what version of drf are you using? can we have a look at your stack trace

**Comment by rohitranjan1991** [comment]
I just got it working correctly. Later i came to know that you can refresh the token only till the time the older token has not expired.

**Comment by JoelOtter** [comment]
Seeing this issue on:

```
Django==1.9.1
djangorestframework==3.3.2
djangorestframework-jwt==1.7.2
```

(All installed via Pip on Python 2.7).

**Comment by jpadilla** [comment]
@JoelOtter there ya go, I'll improve that by using `ImportError`. Thanks!

**Comment by jpadilla** [comment]
@JoelOtter want to give that latest commit a try?

**Comment by JoelOtter** [comment]
@jpadilla Yep, that fixes it for me, thanks.

**Comment by FabrizioA** [comment]
I've the same problem 
Django==1.9.1
djangorestframework==3.3.2
djangorestframework-jwt==1.7.2

I'll try the latest commit. If the latest commit will works for me, when the new version will release?
Thanks.
