### ISSUE TITLE
Using JWT in Allauth

### ISSUE THREAD

**Issue by nym** [GetBlimp/django-rest-framework-jwt#160]
This might be more appropriate for the Allauth repo, but I want to be able to provide SSO beyond just API endpoints. For example, connecting a social account with allauth. Can I reuse the token in order to allow authentication throughout django?

**Comment by techscientist** [comment]
Any updates on this? I am also looking to integrate JWT with Allauth for my Django Rest Framework Api...

**Comment by jpadilla** [comment]
That might be out of the scope of this package. I'm not sure how or where exactly this fits when using allauth. If anyone wants to tackle and contribute back I'd be willing to help. Closing for now.

**Comment by SohaibShafiq1** [comment]
Hi...!!!!
I am a beginner...!!!!!
Can i use allauth only for login/signup/reset/verify/etc and jwt for others like get aoi's request and and post apis request
