### ISSUE TITLE
Authenticate without password

### ISSUE THREAD

**Issue by stunaz** [GetBlimp/django-rest-framework-jwt#162]
Hi, is there any internal method that I can use to get a token but without a password ?
So knowing the user ID (or email or password), I would like to get a valid token for the given user (not knowing the password)?
Is there a method that I can call or modify to do that?

**Comment by Alex3917** [comment]
I just made a pull request with documentation for manually generating a token:

https://github.com/GetBlimp/django-rest-framework-jwt/pull/163

This is suitable for returning a token after account generating. However, you would still need a `user` object in order for this to work.

If you really want to create a token without having a logged in user, you can do that by writing a custom
`jwt_custom_payload_handler` method. Then you just need to register that method in your settings module:

JWT_AUTH = {
    ...
    'JWT_PAYLOAD_HANDLER': 'fwdeveryone.django_customizations.jwt_custom_payload_handler',
}

c.f. here for the fields you'd need to include in the payload:
https://github.com/GetBlimp/django-rest-framework-jwt/blob/master/rest_framework_jwt/utils.py

**Comment by stunaz** [comment]
Thank you @Alex3917 I have a user object, i will use it.

**Comment by mstar0125** [comment]
Hello @Alex3917 

Support I am going to use other model "Program" and "api_key" and "api_secret" fields as a "username" and "password". Is it still possible?

If yes, kindly give me some guilds

Regards
