### ISSUE TITLE
Question: behavior as remote wsgi app vs. local runserver

### ISSUE THREAD

**Issue by cerdman** [GetBlimp/django-rest-framework-jwt#166]
Hi,

I have been using this lib for our JWT and it has worked great with `python manage.py runserver` and generating tokens / authenticating tokens with `localhost:8000` but am having problem with the exact same config running as a wsgi app on `mod_wsgi` on apache/2.2.

It basically is behaving like the authentication hook is not there. Config is all the same (and is using the required config settings per the djangorestframework-jwt docs in config.py), the only difference is that I have my django app running in a sub-directory `/django` vs. `/` in local.

In remote, I can POST to my url set with `url(r'^app/login','extensions.rest_framework_jwt.views.obtain_jwt_token')` and get a token issued, but when I use the same token i got back ($TOKEN) to try and access a protected resource ($MY_AUTH_REQUIRING_URL) like so:

```
curl -X GET -H "Content-Type: application/json" \
-H "Authorization: JWT $TOKEN" $MY_AUTH_REQUIRING_URL
```

I get:
```
{
  "detail": "Authentication credentials were not provided."
}
```

Not sure what I might be missing or how I might debug this...

**Comment by cerdman** [comment]
*Issue was solved*
Problem was that Apache / mod wsgi strips the Authorization header before django even gets it.
Had to add:
`WSGIPassAuthorization On`

To apache config for the site.

**Comment by psychok7** [comment]
I was having the same issue with elastic beanstalk and apache, you saved my day
