### ISSUE TITLE
Tokens invalidated if username changes

### ISSUE THREAD

**Issue by valerymelou** [GetBlimp/django-rest-framework-jwt#172]
Hi,
Is it normal behavior to have all tokens of a user invalidated if he changes his username? I browsed the code and noticed that you use get_by_natural_key(username) to fetch the user from the database given his username. That causes refresh and verification of old tokens to fail if the user changes his username. If this is as it is supposed to be please explain me.

**Comment by Alex3917** [comment]
Retrieving the user by id leaks data, because it lets everyone know how many users have registered. Retrieving users by username is preferable for this reason.

**Comment by valerymelou** [comment]
Thanks. Closing this.

**Comment by valerymelou** [comment]
Thanks, closing this.
