### ISSUE TITLE
JSONWebTokenAPIView fails when content is not a valid JSON

### ISSUE THREAD

**Issue by 990px** [GetBlimp/django-rest-framework-jwt#175]
Eg.:

    curl -X POST -H "Content-Type: application/json" -d '{' http://localhost:8000/api-token-auth/

In this case `compat.get_request_data` uses request.DATA which produces an error.

    `request.DATA` has been deprecated in favor of `request.data` since version 3.0, and has been fully removed as of version 3.2.

django-rest-framework v.3+
django-rest-framework-jwt v.latest

**Comment by jpadilla** [comment]
@990px want to put a PR together to fix this?
