### ISSUE TITLE
Header in docs is incorrect

### ISSUE THREAD

**Issue by AmirTugi** [GetBlimp/django-rest-framework-jwt#178]
In the docs, the header's name is 'Authorization', but in the JSONWebTokenAuthentication, I see that it searches for 'HTTP_AUTHORIZATION'. 
Is that a mistake in the docs, or was I just missing something?

**Comment by ajostergaard** [comment]
http://tools.ietf.org/html/rfc1945#section-10.2

**Comment by jpadilla** [comment]
It's correct as it is. Don't know the whole story/reason behind it, but it is probaby in the wsgi spec. Your client needs to send the the `Authorization` header. When getting the header from the request, you'd see it under `HTTP_AUTHORIZATION`.
