### ISSUE TITLE
Django Deprecation Warning for string in url.

### ISSUE THREAD

**Issue by karthik-rp** [GetBlimp/django-rest-framework-jwt#179]
I just migrated to Django 1.9.,
So while using jwt I'm getting the following warning,

**RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10 (got rest_framework_jwt.views.obtain_jwt_token). Pass the callable instead.
  url(r'^api-token-auth/', 'rest_framework_jwt.views.obtain_jwt_token')**

Its not actually an issue right now. I was wondering if there is a callable view or anything which can be used instead of 'rest_framework_jwt.views.obtain_jwt_token' so that it won't be an issue in the near future.

**Comment by jpadilla** [comment]
@karthik-rp This should do.

```python

from rest_framework_jwt.views import obtain_jwt_token

urlpatterns = [
    url(r'^api-token-auth/', obtain_jwt_token),
]
```

**Comment by karthik-rp** [comment]
Ha ha., How the hell didn't I see that.
Thanks.,
