### ISSUE TITLE
Update supported versions

### ISSUE THREAD

**Issue by jpadilla** [GetBlimp/django-rest-framework-jwt#181]
Probably time to drop support for DRF 2.4 and Django 1.6

**Comment by nicholashughes** [comment]
Based off the info in [release 1.8.0](https://github.com/GetBlimp/django-rest-framework-jwt/releases/tag/1.8.0), the support for these were dropped and this issue can be closed.

**Comment by jpadilla** [comment]
@nicholashughes thanks!
