### ISSUE TITLE
Manage tokens between Multiple hosts (domains)

### ISSUE THREAD

**Issue by blaklites** [GetBlimp/django-rest-framework-jwt#186]
Right now, if the Django application is hosting multiple sites, a token generated from one site can be successfully verified and refreshed by another provided they share the same user/database.  This is not always desired. Django also manages session on a per-site basis.

While working on our multi tenant system in Retailephant.com, we faced this issue where tokens generated from a particular channel that we were hosting were successfully verified and refreshed by another.

What about a solution where the setting 'JWT_VERFIRY_HOST', with default = False, can be used to configure the desire behavior of verifying and refreshing a token based on the host?

**Comment by blaklites** [comment]
I have already forked the repo and applied the needed changes, apart from the changes needed inside tests/. 

https://github.com/GetBlimp/django-rest-framework-jwt/compare/master...blaklites:master

**Comment by jpadilla** [comment]
For this specific case you could look into using the JWT `aud` claim to determine the tenant for which the JWT is valid. We have a global setting for this, `JWT_AUDIENCE`.
