### ISSUE TITLE
Token expiration

### ISSUE THREAD

**Issue by FabrizioA** [GetBlimp/django-rest-framework-jwt#187]
How can I set the expire time of the token to 7 days or greater?
I've added JWT_AUTH = {} dictionary on my djangoproject.settings module and changed the 'JWT_EXPIRATION_DELTA': datetime.timedelta(days=7) with no result. I'had also set 'JWT_VERIFY': True but the token expire in few minutes :(

**Comment by jpadilla** [comment]
Did you figure out what was wrong?

**Comment by FabrizioA** [comment]
Hi @jpadilla, no :(
Do you have the same issue?

**Comment by TaddWood** [comment]
@FabrizioA did you set JWT_REFRESH_EXPIRATION_DELTA ?

**Comment by angvp** [comment]
This is duplicated of #92 closing
