### ISSUE TITLE
critical vulnerabilities affect this package?

### ISSUE THREAD

**Issue by niklasp** [GetBlimp/django-rest-framework-jwt#188]
See here: [https://auth0.com/blog/2015/03/31/critical-vulnerabilities-in-json-web-token-libraries/](https://auth0.com/blog/2015/03/31/critical-vulnerabilities-in-json-web-token-libraries/)
Is that an issue here?

**Comment by jpadilla** [comment]
This package uses PyJWT which addressed those vulnerabilities.
