### ISSUE TITLE
`JWT_ISSUER` Not included in token encode

### ISSUE THREAD

**Issue by chrisforrette** [GetBlimp/django-rest-framework-jwt#189]
I followed the instructions in the docs setting up an end point for auth and another for token verification and also set the `JWT_ISSUER` setting. I was confused to find that, upon receiving a token and turning around and trying to verify it with the other endpoint that it failed due to a missing issuer exception. I dug into the source and saw that this is apparently intentional and in the unit tests the issuer is set manually after the `jwt_payload_handler` function is run:

https://github.com/GetBlimp/django-rest-framework-jwt/blob/master/tests/test_utils.py#L132

I'm fairly new to JWT so I might be misunderstanding something, but shouldn't the `iss` key with the `JWT_ISSUER` setting value be set in the encode step? I'm happy to make a pull request if that is the case. Thanks!

**Comment by blaklites** [comment]
@chrisforrette I found the same issue. Seems like the payload does not have the 'iss' from the JWT_ISSUER settings and thus when we have set a JWT_ISSUER, it is verified while decoding but not set while encoding. @jpadilla is there any reason for this?

**Comment by chrisforrette** [comment]
@jpadilla Thanks :)
