### ISSUE TITLE
Refresh token not working

### ISSUE THREAD

**Issue by mtmithani** [GetBlimp/django-rest-framework-jwt#190]
I'm using all the default settings (including the default URLS), and using CURL to refresh the token but I get the following error:

{"non_field_errors":["orig_iat field is required."]}

Any idea why this error is occurring?

**Comment by Odahi** [comment]
Refresh tokens are *not* enabled by default. You have to overwrite `JWT_AUTH` in `settings.py`:

```python
JWT_AUTH = {
    ...
    'JWT_ALLOW_REFRESH': True,
}
```

**Comment by kodeine** [comment]
@hacknaked is it possible to get the refresh token on login. so it gives token and refresh token both.

**Comment by hacknaked** [comment]
@kodeine It's good to know that. Thanks!

**Comment by c-bata** [comment]
Why the default value of this option is `False` ?
I cannot imagine the situation that it doesn't required.

**Comment by ajostergaard** [comment]
@c-bata I can't imagine a situation where it is required or where it's a good idea. :)

@hacknaked I believe @kodeine was asking a question though lack of question mark does leave it open to debate. :)

**Comment by c-bata** [comment]
@ajostergaard Surely you're right.
I should not have debate my question on this issue. Sorry.

**Comment by sadan** [comment]
I am still facing this issue in v 1.11.0. These are my JWT settings

```
{
    'JWT_EXPIRATION_DELTA': datetime.timedelta(seconds=259200),  # 3 days
    'JWT_REFRESH_EXPIRATION_DELTA': datetime.timedelta(seconds=259200),  # 3 days
    'JWT_AUTH_COOKIE': 'JWT',
    'JWT_ALLOW_REFRESH': True
}
```

**Comment by rapando** [comment]
Still getting the same error even with this in my settings.py

```py
JWT_AUTH = {
    'JWT_VERIFY': True,
    'JWT_VERIFY_EXPIRATION': True,
    'JWT_LEEWAY': 0,
    'JWT_EXPIRATION_DELTA': datetime.timedelta(seconds=300),
    'JWT_ALLOW_REFRESH': True,
    'JWT_REFRESH_EXPIRATION_DELTA': datetime.timedelta(days=7),
}
```

**Comment by mbabazadeh** [comment]
still facing this error!

**Comment by ericovva** [comment]
still facing this error!

**Comment by rachiteagles** [comment]
i used  these settings and it worked

JWT_AUTH = {
    'JWT_ALLOW_REFRESH':True,
    'JWT_EXPIRATION_DELTA': datetime.timedelta(hours=1),
    'JWT_REFRESH_EXPIRATION_DELTA': datetime.timedelta(days=7),
}
