### ISSUE TITLE
signals when login

### ISSUE THREAD

**Issue by stunaz** [GetBlimp/django-rest-framework-jwt#193]
Hi,
Would be great to get a signal when a user successfully login with his username/password. (in other words when the call to` rest_framework_jwt.views.obtain_jwt_token` is successfull).

**Comment by blaklites** [comment]
@stunaz , the obtain_jwt_token view is not really similar to a login view. This has been discussed in https://github.com/GetBlimp/django-rest-framework-jwt/pull/171 and also in https://github.com/tomchristie/django-rest-framework/issues/3869. Basically, it is better to leave the user_logged_in signal usage to the developer.

**Comment by stunaz** [comment]
ok, I get that, but could we get a different signal for that?

**Comment by blaklites** [comment]
That can be done in your customized view which you can create by sub-classing the rest_framework_jwt.views.obtain_jwt_token view, this is specific to your use case

**Comment by stunaz** [comment]
it doesnt have to be specific to  my case. Once a token is create, a signal called maybe `token_obtained` can be dispatched.And then everyone according to their needs can listen to the signal and whatever they want to do.

**Comment by blaklites** [comment]
Like this we can have various signals for various views. For these cases, the developers can subclass the view and create their own signals if needed. Having the signal within the library in the first place does not seem right

**Comment by stunaz** [comment]
why it is not right? sending signals is part of django, signals can be send on certain event. A lot of libraries does that. Of course I can subclass, but I dont want to because I dont want to maintain that and deal with all the future updates. I prefer to use lib as is.

**Comment by stunaz** [comment]
I am going to close this ticket and open another one with a proper title.
https://github.com/GetBlimp/django-rest-framework-jwt/issues/195
