### ISSUE TITLE
Need to receive signals when a token is created

### ISSUE THREAD

**Issue by stunaz** [GetBlimp/django-rest-framework-jwt#195]
Hi,
Would be great to get a signal when a user successfully obtain a token with his username/password.

**Comment by jpadilla** [comment]
After reviewing #194 #171 and giving this more thought, if you want or need a different behavior you should customize. So perhaps you'll need to customize `ObtainJSONWebToken` and trigger the signal you want somewhere in there.

**Comment by robsco-git** [comment]
Here's how I solved it:

settings.py
```python
from django.contrib.auth.signals import user_logged_in

def jwt_response_payload_handler(token, user=None, request=None):
    if user and request:
        user_logged_in.send(sender=user.__class__, request=request, user=user)
    return {
        'token': token,
    }

JWT_AUTH = {
    'JWT_RESPONSE_PAYLOAD_HANDLER': jwt_response_payload_handler,
}
```

models.py
```python
from django.contrib.auth.signals import user_logged_in

def login_handler(sender, user, request, **kwargs):
    print('logged in')

user_logged_in.connect(login_handler)
```

Anything to be concerned about with this approach?

**Comment by bbmhmmad** [comment]
> Here's how I solved it:
> 
> settings.py
> 
> ```python
> from django.contrib.auth.signals import user_logged_in
> 
> def jwt_response_payload_handler(token, user=None, request=None):
>     if user and request:
>         user_logged_in.send(sender=user.__class__, request=request, user=user)
>     return {
>         'token': token,
>     }
> 
> JWT_AUTH = {
>     'JWT_RESPONSE_PAYLOAD_HANDLER': jwt_response_payload_handler,
> }
> ```
> 
> models.py
> 
> ```python
> from django.contrib.auth.signals import user_logged_in
> 
> def login_handler(sender, user, request, **kwargs):
>     print('logged in')
> 
> user_logged_in.connect(login_handler)
> ```
> 
> Anything to be concerned about with this approach?

According to [DRF JWT Documentation](url):

> jwt_response_payload_handler is responsible for controlling the response data returned after login or refresh. Override to return a custom response such as including the serialized representation of the User.

This would trigger logged in signal for login and refresh not just login.
