### ISSUE TITLE
override payload settings fails

### ISSUE THREAD

**Issue by dbinetti** [GetBlimp/django-rest-framework-jwt#197]
I am using the native models.UUIDField as my primary key in my Custom User model (which also uses email address as the USERNAME_FIELD.)  

The default implementation calls `user_id = user.pk`, which returns a UUID Instance instead of the actual identifying string.

Now I can see that I should probably override `JWT_PAYLOAD_HANDLER` with a function that ignores the `user_id` key, but in trying I keep getting random errors like "you need to set your SECRET_KEY" even though it is set. 

So my question is: how best to override the payload handler?  Where should that function live?  It refers to the conf.settings, but then the function is also supposed to live (or be imported into) the settings file itself?  Doesn't that cause a circular dependency?  

This might be more a django issue than a DRF-JWT issue, but I'm truly lost...

**Comment by pazooki** [comment]
I'm facing the same issue

**Comment by jpadilla** [comment]
Any chance you could share an example project that can be used to reproduce?

**Comment by dbinetti** [comment]
https://github.com/dbinetti/jwt

**Comment by jpadilla** [comment]
@dbinetti need steps to reproduce your original issue. Don't see any custom `JWT_PAYLOAD_HANDLER`

**Comment by dbinetti** [comment]
I may have found something else; i'll open a new ticket for that.

**Comment by dbinetti** [comment]
Closing in favor of #201
