### ISSUE TITLE
Authorization header: bearer vs. jwt

### ISSUE THREAD

**Issue by dfeinzeig** [GetBlimp/django-rest-framework-jwt#199]
The docs say to set the authentication header to jwt, but it seems the standard is to use bearer.  Any reason that jwt is preferred?

**Comment by jpadilla** [comment]
definitely not a standard, but thanks for this question. We made the decision out of #4.

**Comment by dfeinzeig** [comment]
Ah ok, thanks for the pointer.  That clarifies.
