### ISSUE TITLE
Overriding JSONWebTokenSerializer.validate() to auth based on 3rd party response and not user model?

### ISSUE THREAD

**Issue by aendra-rininsland** [GetBlimp/django-rest-framework-jwt#2]
Hi there!

I'm a bit of a Python neophyte so huge apologies if this is way more obvious than I'm making it out to be, but any suggestions how I'd override JSONWebTokenSerializer.validate() so that, instead of validating against [django.contrib.auth.authenticate() here](https://github.com/GetBlimp/django-rest-framework-jwt/blob/master/rest_framework_jwt/serializers.py#L27), it passes the details to a 3rd-party API and then validates based on a response from that?

(Essentially, I work at a news org with a giant non-metered paywall, and I need to pass details from the user's paywall cookie to the paywall API to validate that it's a valid cookie. I'm thinking DRFJWT will then generate a JWT that gets passed back to the user, and then every request thereafter just validates based on that, thus reducing load on the paywall API. If I'm totally out to lunch with my thinking, please let me know.)

Thanks!

**Comment by alexkiburu** [comment]
@jpadilla  3 years later and it still helps. Awesome stuff
