### ISSUE TITLE
Support for automatic creation of users based on JWT payload

### ISSUE THREAD

**Issue by jobec** [GetBlimp/django-rest-framework-jwt#204]
It would be great to have some sort of support for creating users when they don't exists yet.
A bit like django-auth-ldap does if [this function](https://bitbucket.org/psagers/django-auth-ldap/src/780dee4375316681cf331e5174a8006b72087b84/django_auth_ldap/backend.py?at=default&fileviewer=file-view-default#backend.py-218)

django-auth-ldap also links LDAP groups the user is member of to django groups with the same name. If these groups could also be fetched from the JWT payload, that would instantly make this module capable of linking a django project to, for example, Active Directory by consuming microsoft ADFS 3.0 JWT tokens without the need for django-auth-ldap or creating the users beforehand.

I managed to create users by overriding the `jwt_get_username_from_payload_handler` function by setting `JWT_PAYLOAD_GET_USERNAME_HANDLER` to point to a custom function like below, but having it build in would be nice:
```python
from django.contrib.auth import get_user_model


def jwt_get_username_from_payload_handler(payload):
    model = get_user_model()
    username = payload.get('username')
    username_field = getattr(model, 'USERNAME_FIELD', 'username')

    kwargs = {
        username_field + '__iexact': username,
        'defaults': {username_field: username.lower()}
    }

    model.objects.get_or_create(**kwargs)
    return username
```

**Comment by jpadilla** [comment]
Definitely out of scope for this package.
