### ISSUE TITLE
A question about self-contained feature in JWT

### ISSUE THREAD

**Issue by eyscode** [GetBlimp/django-rest-framework-jwt#205]
Hello, in the definition of JWT says:

> **Self-contained**: The payload contains all the required information about the user, to avoid querying the database more than once.

I wanna emphasize this part "avoid querying the database" because I thought your implementation of JWT wouldn't hit the database since the token payload contains almost all the user data (or some fields at least). But after seen the method authenticate_credentials in BaseJSONWebTokenAuthentication, it hits the database in order to get a user instance:
```
user = User.objects.get_by_natural_key(username)
```
So my question is the following: Is it impossible to create like a "fake instance" of the user model just with the payload fields and whenever a field not contained in the payload is accessed just hit the database to retrieve that field? Something like the behavior when using *deffer* and *only* methods on Django query manager. If we achieve this then we really take advantage of the self-contained feature, but I'm aware this could be a Django ORM limitation.

Anyway I would like to know the reasons behind the decision of querying the database on each authentication process. Thanks in advance.

**Comment by anx-ckreuzberger** [comment]
I believe it says "more than once" for a reason. You need to query it once to get the actual user details, but you don't need to do query the session table for the session id.
