### ISSUE TITLE
JWT_AUTH_HEADER_PREFIX Changes Authorization Header but Not WWW-Authenticate

### ISSUE THREAD

**Issue by cancan101** [GetBlimp/django-rest-framework-jwt#207]
`JWT_AUTH_HEADER_PREFIX` is not being used when [constructing the `WWW-Authenticate` header](https://github.com/GetBlimp/django-rest-framework-jwt/blob/df2a01c48dc0d7b804577cb9f94863b54a32d8de/rest_framework_jwt/authentication.py#L104). Currently that value is hardcoded to `JWT`.

**Comment by jpadilla** [comment]
@cancan101 good catch, wanna put together a PR? :smiley:

**Comment by jpadilla** [comment]
@cancan101 want to put a PR together?

**Comment by cancan101** [comment]
sure
