### ISSUE TITLE
[Proposal] Login using Auth0 JWT token in a django rest framework API

### ISSUE THREAD

**Issue by mcueto** [GetBlimp/django-rest-framework-jwt#220]
Hi colleagues!

I'd working on some modifications to make easy and fast to use Auth0 in any Django Rest Framework app using this library and i want to propose the following approach to do that:

- **Generate a new setting attribute to select the field name given to the username in the returned payload** this could be used to easily specify that without need to create(or copy) and configure a specific handler in each API we create. The current stable version of the library has

> def jwt_get_username_from_payload_handler(payload):
    """
    Override this function if username is formatted differently in payload
    """
    return payload.get('username')

and i want to change it to

> def jwt_get_username_from_payload_handler(payload):
    """
    Override this function if username is formatted differently in payload
    """
    return payload.get(api_settings.JWT_PAYLOAD_USERNAME_FIELD)

with default JWT_PAYLOAD_USERNAME_FIELD setted to 'username'

- **add a configuration field to specify if auth0 is being used, validate it and use the `base64.b64decode` function used by Auth0** to decode the Auth0 secret, the field would be something like `JWT_IS_AUTH0` with default to `False`

At the end of `rest_framework_jwt/settings.py` add the following code:
>if(api_settings.JWT_IS_AUTH0):
    api_settings.JWT_SECRET_KEY=base64.b64decode(api_settings.JWT_SECRET_KEY.replace("_","/").replace("-","+"))

-**Auto-Create users based on the username** instead of use of `get_by_natural_keys` to retrieve the user in the `authenticate_credentials` function from `rest_framework_jwt` use `get_or_create(username)` with the given username -`sub` field in Auth0 returned payload-. It's a sort of "stateless user" which allows us to simply asociate anything in our rest apis with the current user in the system. obviously i want to check if it works well with the current login scenarios to not to break anything

'The username in an Auth0 must be -for example- the `sub` attribute in the payload returned, so it's unique and let us to properly identify the current user'

The code i want to include is the following
>response = User.objects.get_or_create(username=username)
            created = response[1]
            user = response[0]
            if created:
                user.save()

I hope to hear from you soon. Any feedback would be apreciated

Grettings from Chile

**Comment by orf** [comment]
Hi, I'm personally against adding any auth0 specific settings to this
library, I think it can be handled better without.

**Comment by mcueto** [comment]
>  I think it can be handled better without.
@orf the auth0 or the djangorestframework-jwt itself??

**Comment by mcueto** [comment]
I finally created an app to do auth0 authentication using djangorestframework-jwt, you can view it on: [djangorestframework-auth0](https://github.com/mcueto/djangorestframework-auth0)

So i mark this issue as closed

Greetings!

**Comment by saius** [comment]
Please restframwork-jwt assume that you have already registered user. 
in my case, I want to authenticate user via auith0 and then create them in my django app.

how could i do this?

Thanks

**Comment by mcueto** [comment]
@saius , just use https://github.com/mcueto/djangorestframework-auth0 ;)

**Comment by kishanm0794** [comment]
I am able to get the username. How do I get the `email` and `email_verified` by using `Auth0JSONWebTokenAuthentication`
