### ISSUE TITLE
Do a new release

### ISSUE THREAD

**Issue by PierreF** [GetBlimp/django-rest-framework-jwt#222]
The latest release is 7 month old and some commit on master are really useful (I think to DRF 3.2+ support - commit 7adfe48) .
Before the new release, could you merge PR #221 ?

**Comment by carltongibson** [comment]
https://github.com/GetBlimp/django-rest-framework-jwt/releases/tag/1.8.0

https://pypi.python.org/pypi/djangorestframework-jwt/1.8.0

Enjoy.

**Comment by PierreF** [comment]
Thanks!
