### ISSUE TITLE
Docs are out of date in github.io 

### ISSUE THREAD

**Issue by shanemgrey** [GetBlimp/django-rest-framework-jwt#227]
The content in [this link](http://getblimp.github.io/django-rest-framework-jwt) from the main readme are old docs and contain information that doesn't work in the current version.

**Comment by carltongibson** [comment]
Fixed by https://github.com/GetBlimp/django-rest-framework-jwt/commit/f02cda6e9700a94a9f6f65364673a8a52390b7a0

**Comment by shanemgrey** [comment]
@carltongibson It seems this update to the github.io docs didn't include the most recent update to the docs that I did a PR for around the same time.  Must have been done in the other order.  The PR was a very minor change to password length in the examples, but worth saving new users a bit of hassle when they are copy pasting.

**Comment by carltongibson** [comment]
OK. Noted
