### ISSUE TITLE
401 vs 403 on expired token.

### ISSUE THREAD

**Issue by dmwyatt** [GetBlimp/django-rest-framework-jwt#229]
I've a client who thinks the response when doing a request with an expired token should be a 401 instead of the 403 Django does currently.  AFAICT the 403 happens because that's just the way `drf-jwt` interacts with Django.

Anyone have any thoughts on which is more appropriate and if 401 is more appropriate a decent way of making that happen?

**Comment by carltongibson** [comment]
DRF's `AuthenticationFailed` raises with a `401` — what's the exact code path you're hitting? 

(Unless you're prepared to override something yourself, it's going to be a "Meh. Can't help" — Sorry)

**Comment by dmwyatt** [comment]
@carltongibson When I try a request with a token that is expired I get a 403, and the body contains  `{'detail': 'Signature has expired.'}`

It turns out that `AuthenticationFailed` [doesn't always raise a 401](http://www.django-rest-framework.org/api-guide/authentication/#unauthorized-and-forbidden-responses).  I removed `SessionAuthentication` and `BasicAuthentication` from my `DEFAULT_AUTHENTICATION_CLASSES` which fixes my issue.

**Comment by carltongibson** [comment]
The behaviour you're referring to comes from DRF's `exception_handler` function https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/views.py

Glad you resolved it. 👍🏽
