### ISSUE TITLE
Calling a serializer requires context.

### ISSUE THREAD

**Issue by shanemgrey** [GetBlimp/django-rest-framework-jwt#230]
The docs and comments for JWT_RESPONSE_PAYLOAD_HANDLER suggest the following to add the serialized user to the response.  But that produces an error that I detailed in [This SO Post.](http://stackoverflow.com/questions/36583243/error-overriding-jwt-response-payload-handler-to-add-serialized-user)

The following change works, but I'm not totally clear on what the Serializer is requiring and if this is a workaround that should be done differently.

Want a PR to change the comments and docs to this?

    return {
        'token': token,
        'user': UserSerializer(
            user,
            context={
                'request': request},
            ).data
    }

**Comment by carltongibson** [comment]
DRF's `Hyperlinked...` fields use the `request` to generate the URL for the hyper link — that's why they need it. 

> Want a PR to change the comments and docs to this?

Yeah. That would be great!
