### ISSUE TITLE
last_login does not get updated

### ISSUE THREAD

**Issue by djorgesen** [GetBlimp/django-rest-framework-jwt#235]
There is a field in the user model of the django.contrib.auth called last_login. This gets updated by the update_last_login function of which I think is fired upon login to the admin. 

neither 
rest_framework_jwt.views.obtain_jwt_token
or
rest_framework_jwt.views.refresh_jwt_token
updates this field in the user model.

Is this by design?

**Comment by carltongibson** [comment]
Can you improve the issue description please?

**Comment by djorgesen** [comment]
I think that is more specific.

**Comment by carltongibson** [comment]
> Is this by design?

It's by design. [`JSONWebTokenAPIView.post`](https://github.com/GetBlimp/django-rest-framework-jwt/blob/master/rest_framework_jwt/views.py#L53-L63) fetches the `user` but **does not** update it. 

You're welcome to override this method if you need different behaviour.

**Comment by tangcongyuan** [comment]
In case anyone is wondering how to overwrite:
http://stackoverflow.com/questions/21349418/django-1-6-where-is-the-user-field-last-login-updated
Just add those two line code to [JSONWebTokenAPIView.post](https://github.com/GetBlimp/django-rest-framework-jwt/blob/master/rest_framework_jwt/views.py#L53-L63)

**Comment by dudanogueira** [comment]
Here it goes:

It would be nice to have a configurable setting to enable/disable this fuctionality, or at least a signal so you can dispatch it from.

```
from rest_framework_jwt.settings import api_settings
from django.utils import timezone
jwt_response_payload_handler = api_settings.JWT_RESPONSE_PAYLOAD_HANDLER
from rest_framework.response import Response
from datetime import datetime
from rest_framework import status

class MeuObtainJSONWebToken(ObtainJSONWebToken):
    def post(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)

        if serializer.is_valid():
            user = serializer.object.get('user') or request.user
            user.last_login = timezone.now()
            user.save(update_fields=['last_login'])
            token = serializer.object.get('token')
            response_data = jwt_response_payload_handler(token, user, request)
            response = Response(response_data)
            if api_settings.JWT_AUTH_COOKIE:
                expiration = (datetime.utcnow() +
                              api_settings.JWT_EXPIRATION_DELTA)
                response.set_cookie(api_settings.JWT_AUTH_COOKIE,
                                    token,
                                    expires=expiration,
                                    httponly=True)
            return response

        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

obtain_jwt_token = MeuObtainJSONWebToken.as_view()
```

**Comment by Maksych** [comment]
```python
from django.contrib.auth.models import update_last_login

from rest_framework_jwt import serializers


class JWTSerializer(serializers.JSONWebTokenSerializer):
    def validate(self, attrs):
        validated_data = super().validate(attrs)
        update_last_login(None, validated_data['user'])
        return validated_data


class AccountLoginAPIView(ObtainJSONWebToken):
    serializer_class = JWTSerializer
```
