### ISSUE TITLE
Can I exclude selective Django endpoints from JWT Authentication ?

### ISSUE THREAD

**Issue by svalleru** [GetBlimp/django-rest-framework-jwt#238]
If I enable JWT Authentication for my django app, it's gonna authenticate every endpoint, problem with that is, If I have APIs for signup, login & forgotpassword, I'd never be able to use them in the first place to get the auth token and use it for subsequent communication.

Alternatively, I can add a user with 'python manage.py createsuperuser' from CLI - but this is cumbersome

Appreciate any thoughts

**Comment by jpadilla** [comment]
Authentication schemes are either set globally or per-view(set). http://www.django-rest-framework.org/api-guide/authentication/#setting-the-authentication-scheme

**Comment by svalleru** [comment]
Nice, this is good !

**Comment by SolessChong** [comment]
@svalleru @jpadilla Just for supplement, you can still specify exceptions on authentication when set globally. E.g. in DRF class-based view, you can do as such:

```
REST_FRAMEWORK = {
    # other settings...

    'DEFAULT_AUTHENTICATION_CLASSES': [],
    'DEFAULT_PERMISSION_CLASSES': [],
}
```

**Comment by Allan-Nava** [comment]
@SolessChong But is possible implement the JSONWebAuthentication with ModelViewSets ? 

Thanks

**Comment by kartikkarmaran** [comment]
to exclude limited number of your views from default authentication and permission settings add per view based settings but pass in nothing.
for function based views:
 @authentication_classes(())
@permission_classes(())
for class based views:
permission_classes = ()
 authentication_classes = ()
rest-jwt will then allow to access pages without token.

**Comment by olivierpons** [comment]
Hi, I'm using djangorestframework with djangorestframework-simplejwt.

Everything works fine except one thing: I want to access to a reset-password view with a `POST` method (= REST "create").

    from django.views.decorators.csrf import csrf_exempt
    from rest_framework.generics import CreateAPIView

    # JSON views are never accessed through classical forms = no csrf possible:
    @method_decorator(csrf_exempt, name='dispatch')
    class UsersResetPasswordView(CreateAPIView):
    
        serializer_class = UserResetPasswordSerializer
        permission_classes = [permissions.AllowAny]
    
        def create(self, request, *args, **kwargs):
            return Response({'reset-url': 'test url'},
                            status=status.HTTP_202_ACCEPTED, headers=headers)
    
        def post(self, request, *args, **kwargs):
            return self.create(request, *args, **kwargs)


`permissions.AllowAny` is not enough, I get a `401` "`Given token not valid`" (if I send the token, otherwise I get "`forbidden`").

I've tried to add `authentication_classes = []` but nothing changes.

*I just want to make a simple view that anybody can access, via a `POST`!*

The `UserResetPasswordSerializer` is the simplest `Serializer` you can make:

    class UserResetPasswordSerializer(serializers.Serializer):
    
        email = serializers.EmailField(required=False, allow_blank=True,
                                       allow_null=True)
        username = serializers.CharField(required=False, allow_blank=True,
                                         allow_null=True)
    
        def create(self, validated_data):
            # do nothing
            return None
    
        def update(self, instance, validated_data):
            # do nothing
            return instance

How can I do?
