### ISSUE TITLE
Need user id with token

### ISSUE THREAD

**Issue by aashishsoni** [GetBlimp/django-rest-framework-jwt#250]
I am stuck with the JWT, can any one tell me how can I get user ID along with token.

My url.py :

```
from webservices import views

router = routers.DefaultRouter()
router.register(r'api/users', views.UserViewSet)


urlpatterns = [
url(r'^admin/', include(admin.site.urls)),
url(r'^api/login/', obtain_jwt_token),
]
```

**Comment by vaibhav-jain** [comment]
@aashishsoni Share you view.py ??

**Comment by aashishsoni** [comment]
First of all thanks Vaibhav for the prompt reply, here is my 

view.py
`from rest_framework import viewsets, permissions
from django.contrib.auth.models import User

class UserViewSet(viewsets.ModelViewSet):

    queryset = User.objects.all()
    serializer_class = UserSerializer`

serializers.py
`from django.contrib.auth.models import User
from rest_framework import serializers

class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ('id', 'username', 'email')`

**Comment by vaibhav-jain** [comment]
My pleasure.  First of all obtain_jwt_token is just to obtain token not for login. I believe you are using rest Auth???  Which supports this package and after successful login it will give you token with other user details and if you want to add more details it is easy to override the UserDetailsSerializer and add details as you want.  Hope it helps

**Comment by aashishsoni** [comment]
Actually I am not getting the procedure to get user detail from jwt token, can you send me example code for the same I mean url.py, view.py and serializers.py. it will be very help full for me.

**Comment by SalahAdDin** [comment]
@aashishsoni  You can use ` three times before and after your code for give format it.

**Comment by aashishsoni** [comment]
@SalahAdDin just updated thanks for the suggestion

**Comment by vaibhav-jain** [comment]
```
#urls.py

urlpatterns = [
    url(r'^login/$', rest_auth_views.LoginView.as_view(), name='login')
]

# Rest Auth settings.py

REST_AUTH_SERIALIZERS = {
    'JWT_SERIALIZER': 'apps.api.serializers.JWTSerializer',
}

#Custom JWT_SERIALIZER to Use Custom UserDetailsSerializer
from rest_auth.serializers import JWTSerializer as RestAuthJWTSerializer

class JWTSerializer(RestAuthJWTSerializer):
    """
    Serializer for JWT authentication.
    Just to override rest_auth default UserDetailsSerializer.
    Used during login.
    """
    token = serializers.CharField(read_only=True)
    user = UserDetailsSerializer()

user = UserDetailsSerializer() Where you can specify your Custom Serializer.

Using Default Rest Auth LoginView
```

**Comment by vaibhav-jain** [comment]
```
Restauth Authentication class BaseJSONWebTokenAuthentication has authenticate_credentials
method which uses jwt_get_username_from_payload to get username and then look for User in
DB have look at this if you just want Username from token 

```

**Comment by angvp** [comment]
Closing this, reopening if anything.
