### ISSUE TITLE
Django 1.10 support

### ISSUE THREAD

**Issue by angvp** [GetBlimp/django-rest-framework-jwt#251]
I've started migration of my project to Django 1.10 so far I found some issues on test suite when running Django 1.10, I've updated some of the tests, but some of them are still failing.. I'll re work on this later but if someone already started giving support to Django 1.10 this is a good start [1]

[1] https://github.com/angvp/django-rest-framework-jwt

**Comment by SalahAdDin** [comment]
Put your code here friend.

**Comment by angvp** [comment]
@SalahAdDin There's a link upside ^ ;) .. I'm opening a pull request anyway

**Comment by nicholashughes** [comment]
Did this get closed? The docs list Django 1.10 as a requirement but this comment suggests otherwise.
