### ISSUE TITLE
Update PyPI to 1.8.x

### ISSUE THREAD

**Issue by Karimerto** [GetBlimp/django-rest-framework-jwt#272]
I would very much like to use the public/private key pair when encoding and decoding the tokens, and do so using this from PyPI. However the current version (1.8.0) does not support such keys, even though the documentation says so.

I can always write my own `jwt_??code_handler` -functions, but that does seem rather pointless as the proper support is already in place. Could you upload a more recent version of this to PyPI?

**Comment by angvp** [comment]
I think this is old current version (at the moment of closing this issue is 1.9.0 [0])

[0] https://pypi.python.org/pypi/djangorestframework-jwt/1.9.0
