### ISSUE TITLE
Make a PyPI release to add Django 1.10 support?

### ISSUE THREAD

**Issue by mblayman** [GetBlimp/django-rest-framework-jwt#289]
The 1.8 version of DRF-JWT does not work with Django 1.10 (released in August). The master branch merged support for 1.10 back in September. Are there any blockers that are preventing a 1.9 release of DRF-JWT?

(As a fellow maintainer of open source projects, I don't mean to nag. 😇  I'm curious if there's any way I can help because I have projects where this is my last remaining dependency that will not work with Django 1.10.)

**Comment by jpadilla** [comment]
No blockers that I'm aware at the moment, just short on time to review further issues or pull requests. I'll definitely schedule some time this week to get a release out.

**Comment by mblayman** [comment]
Thanks, I appreciate it!

**Comment by jpadilla** [comment]
@mblayman just published v1.9.0, thanks again!

**Comment by mblayman** [comment]
Dude! You rock!

**Comment by jpadilla** [comment]
@mblayman thanks for helping out and contributing.
