### ISSUE TITLE
how to remove/delete token when a user logouts?

### ISSUE THREAD

**Issue by cjdp25** [GetBlimp/django-rest-framework-jwt#291]
I was looking for a solution to make a centralized login server, (see my question in stackoverflow: http://stackoverflow.com/questions/41166704/how-to-make-centralized-login-server-with-django/41166913#41166913 ) and I managed to make it work using [djoser](https://github.com/sunscrapers/djoser) and [django-rest-framework-jwt](https://github.com/GetBlimp/django-rest-framework-jwt/) (this project) and I can make the user logins on one site and keeps his session across all subdomains, but now I can't remove/delete the token generated to that user when he logs out on the client app, because if I use its token for example with a ```curl -X POST http://login.example.com/me/ -H 'Authorization: JWT <token_here>'``` I get a valid user's session even when the user logged out from web browser (I can flush cookies from browser and when user go to another app URL, he couldn't login).

I see I can ```obtain_jwt_token```, ```refresh_jwt_token``` and ```verify_jwt_token``` but I can't remove/delete token... how can I do it?

**Comment by shanemgrey** [comment]
One workaround I've found that might apply to your issue is to simply move the `'rest_framework_jwt.authentication.JSONWebTokenAuthentication',` to the top like so: 

```
    REST_FRAMEWORK = {
        'DEFAULT_PERMISSION_CLASSES': (
            'rest_framework.permissions.IsAuthenticated',
        ),
        'DEFAULT_AUTHENTICATION_CLASSES': (
            'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
            'rest_framework.authentication.SessionAuthentication',
            'rest_framework.authentication.BasicAuthentication',
        ),
    }
```

This causes the JWT to be considered first if present, and the session cookie is never looked at.

I haven't found this to cause any other issues, but I haven't used it in production yet. 

 [My SO Q&A on the issue](http://stackoverflow.com/questions/41494671/django-session-causes-angular-with-jwt-token-missing-or-incorrect-error/41494672#41494672)

**Comment by orf** [comment]
Revocation is a hard(TM) problem to solve with jwt. There is no real way to
solve this, tokens can only expire not be revoked.

**Comment by Alex3917** [comment]
Just add a date time field to your user model called something like 'token_last_expired'. Set it to be null by default, and update the timestamp every time the user logs out.

Then just subclass the validation logic to not accept tokens where the issued at date is less than the token_last_expired date. The custom validator should look something like this:

```
from django.utils.dateformat import format

from rest_framework import exceptions
from rest_framework_jwt.authentication import JSONWebTokenAuthentication

class CustomJSONWebTokenAuthentication(JSONWebTokenAuthentication):
    """ Expire token on password change and force user to re-authenticate. """

    def authenticate_credentials(self, payload):
        user = super().authenticate_credentials(payload)

        orig_iat = int(payload['orig_iat'])
        token_last_expired = int(format(token_last_expired, 'U'))
        
        if orig_iat < token_last_expired:
            msg = 'Users must re-authenticate after changing password.'
            raise exceptions.AuthenticationFailed(msg)

        return user
```

**Comment by orf** [comment]
This would work, but only for applications that have access to the primary user database, and not for others that are authenticating against a signed JWT.

If this solution works for you then you should ask if you really need a JWT, and why not use a cookie?

**Comment by joaco1826** [comment]
settings.py
REST_FRAMEWORK = {
    # Custom authentication JSONWebToken
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'myapp.location.CustomJSONWebTokenAuthentication',
    ),
}

#location 
from django.utils.dateformat import format

from rest_framework import exceptions
from rest_framework_jwt.authentication import JSONWebTokenAuthentication


class CustomJSONWebTokenAuthentication(JSONWebTokenAuthentication):
    """ Expire token on password change and force user to re-authenticate. """

    def authenticate_credentials(self, payload):
        user = super().authenticate_credentials(payload)

        orig_iat = int(payload['orig_iat'])
        token_last_expired = int(format(user.token_last_expired, 'U'))

        if orig_iat < token_last_expired:
            msg = 'Users must re-authenticate after logging out.'
            raise exceptions.AuthenticationFailed(msg)

        return user
