### ISSUE TITLE
Replace login with log in in sentences

### ISSUE THREAD

**Issue by rriehle** [GetBlimp/django-rest-framework-jwt#294]
The word 'login' when used as a verb is incorrect in English.  The preferred usage is 'log in' when it is used in a sentence.  This, 'log in', is also more consistent with the Django codebase.  Humbly request review of pending pull request [295](https://github.com/GetBlimp/django-rest-framework-jwt/pull/295) to correct the issue.

**Comment by jpadilla** [comment]
Closed via #295
