### ISSUE TITLE
Are there any plans to add support for Python 3.6?

### ISSUE THREAD

**Issue by jrocketfingers** [GetBlimp/django-rest-framework-jwt#305]
Is there any reason that the library doesn't support 3.6, besides it being only recently released?
I'll make a PR with a version bump later if you don't mind/there are no issues.

**Comment by jpadilla** [comment]
No specific reason. Happy to review a PR for it. Might be worth checking out latest changes to [DRF](https://github.com/tomchristie/django-rest-framework)'s travis/tox setup to see if there's anything we can reuse.

**Comment by jrocketfingers** [comment]
Might've missed something, but I haven't noticed anything handy to add to the build. Curious though, 3.5 onward travis build are run only with Django 1.10, and DRF 3.4/3.5, you're dropping support for 1.9?

**Comment by blueyed** [comment]
Fixed in https://github.com/GetBlimp/django-rest-framework-jwt/commit/5c81e6550ffd5f47e512f4e33f579fe1b30fb226.
