### ISSUE TITLE
How to change the expiration per token

### ISSUE THREAD

**Issue by michaelaelise** [GetBlimp/django-rest-framework-jwt#312]
I just installed jwt and it is going well so far.  I need some tokens to never expire (i.e. set the expire date 100 years from now) and I need some to expire after say 2 hours.
How can I put an expiration on a per token basis?

I imagine override the encode_handler?

Does anyone have a working example of dynamically changing the expiration?

Thank you!

p.s. I apologize, I did not see issue # 311 before I posted this.

**Comment by angvp** [comment]
Duplicated of #311
