### ISSUE TITLE
Connection refuse when test

### ISSUE THREAD

**Issue by andriwarda** [GetBlimp/django-rest-framework-jwt#320]
Hello,
I have found some error when i try to run command `curl -X POST -d "username=admin&password=password123" http://localhost:8000/api-token-auth/`
I have following intruction from docs but i have error 
`curl: (7) Failed to connect to localhost port 8000: Connection refused`

Can you help me ?
Thank's for advance

**Comment by orf** [comment]
Hi, this means you are not running the development server on that port.
This isn't a problem with this library I'm afraid.
