### ISSUE TITLE
HTTP 405 Method Not Allowed

### ISSUE THREAD

**Issue by andriwarda** [GetBlimp/django-rest-framework-jwt#321]
Hello, I'm trying to run django rest framework jwt.
When i run server there's no problem. 
I run `http://127.0.0.1:8000/api-token-auth/` in browser, but i get 
`HTTP 405 Method Not Allowed
Allow: POST, OPTIONS
Content-Type: application/json
Vary: Accept

{
    "detail": "Method \"GET\" not allowed."
}`

In server side `[22/Mar/2017 08:20:08] "GET /api-token-auth/ HTTP/1.1" 405 7480`

But i still get the token when i run `curl -X POST -d "username=admin&password=password123" http://localhost:8000/api-token-auth/`

Can anyone help me ?
Thank's for advance

**Comment by orf** [comment]
Hi, i hate to be curt but your issue contains the reason this is happening.
Your browser is making a GET request, your curl is making a POST. get
requests don't work on the token endpoint, as the server is clearly telling
you.

A simple Google would have shown you the issue.

**Comment by andriwarda** [comment]
Thank's for fast reply, 
Sorry for that,  now i know why i get error. Thank you

**Comment by pkalosh** [comment]
> Thank's for fast reply,
> Sorry for that, now i know why i get error. Thank you

hey what was the cause of this error
