### ISSUE TITLE
Django 1.11

### ISSUE THREAD

**Issue by sadan** [GetBlimp/django-rest-framework-jwt#324]
Any idea when the package will be updated for Django 1.11? Will there be a problem if I use current latest build with Django 1.11?

**Comment by jpadilla** [comment]
@sadan haven't tried it. Would you mind giving it a go and reporting back any issues you might find? Also a PR adding 1.11 to test matrix is a good step forward and is more than welcome.

**Comment by Alex3917** [comment]
I'm running with 1.11 in production and haven't run into any issues. We obviously aren't using every possible configuration option, but none of the core functionality seems to be broken.

**Comment by orf** [comment]
I made a MR to add tests on 1.11, lets see what happens :+1:

**Comment by jpadilla** [comment]
According to #325 we should be good to go. Thank you!

**Comment by psychok7** [comment]
@jpadilla any idea when this is going to be released to pypi?
