### ISSUE TITLE
Look up user with token only

### ISSUE THREAD

**Issue by yarnball** [GetBlimp/django-rest-framework-jwt#327]
Hi,

Great work on this lib.

I'm trying to add security to a socket I've setup. As sockets don't work like regular requests, I've only been able to access the JWT token on it's own.

I am sending only `JWT ey123456` etc.

I simply want to check if the token exists, then return the `user.id` from it.

The below code tells me `AttributeError: 'Token' object has no attribute 'META'`.

```
@channel_session
def ws_connect(message):
    token = [part for part in headercookies.split(';') if 'token=' in part][0].partition('token=')[2]
    fulltoken = ('JWT ' + token)
    user_from_token = Token.objects.filter(key='token').values('user_id')
    try:
        user_jwt = JSONWebTokenAuthentication().authenticate(Token(token))
    except AuthenticationFailed:
        raise PermissionDenied
```

**Comment by djstein** [comment]
What are you importing to get Token?
If you are using: `from rest_framework.authtoken.models import Token`
try making sure that `'rest_framework.authtoken',` is in your installed apps

I am having a similar issue accessing where these tokens are actually stored

**Comment by angvp** [comment]
@yarnball Seems that you're mixing the Token Auth that DRF provides with drf-jwt ? re-open if it's necessary, otherwise I'm closing this issue
