### ISSUE TITLE
Create admin.py (much like DRF authtoken admin.py)

### ISSUE THREAD

**Issue by djstein** [GetBlimp/django-rest-framework-jwt#329]
Many users would benefit greatly from being able to view tokens already made/create new tokens/delete tokens in the Django Admin Panel. Currently DRF has an included admin.py with the `rest_framework.authtoken` app [found here](https://github.com/encode/django-rest-framework/blob/master/rest_framework/authtoken/admin.py).

When the `rest_framework.authtoken` app is installed it still creates a standard DRF token and not one from DRF-jwt. Is there a DRF configuration in settings.py to ensure DRF makes all tokens with JWT? Or can we have a standard admin.py installed with the app with the required fields to show DRF-jwt tokens?

**Comment by parth-choudhary** [comment]
As far as I understand the whole point of JWT is not having to store tokens in the database and create them using algorithms and keys on the fly.

If you still need this, maybe you can write your own table and insert cookies in it using JWT's algo?

**Comment by djstein** [comment]
Thanks, read up on this a few weeks ago. At the time of my previous writing I was under the impression it was being stored in a table like the DRF-auth-token package does.
