### ISSUE TITLE
Invalid signature

### ISSUE THREAD

**Issue by philippeluickx** [GetBlimp/django-rest-framework-jwt#332]
When inputting a JWT key on https://jwt.io/ it actually tells me that the signature is invalid?
Is anyone else having the same issue?

I am using this library through https://github.com/Tivix/django-rest-auth

**Comment by angvp** [comment]
Sorry, this doesn't seem that is necessarily related to the project.

**Comment by philippeluickx** [comment]
@angvp could you please elaborate? It seems to me that this project is using JWT. If the tokens that DRF-JWT are generating can not be validated by a website that follows standards (JWT.IO allows you to decode, verify and generate JWT.), then I do think it is relevant.
I might miss a point here though, certainly possible. But I would appreciate an explanation...
