### ISSUE TITLE
CSS or markup is terrible

### ISSUE THREAD

**Issue by wbeyda** [GetBlimp/django-rest-framework-jwt#337]
The CSS or markup on http://getblimp.github.io/django-rest-framework-jwt/#rest-framework-jwt-auth is really terrible looking.

**Comment by angvp** [comment]
Sorry you don't like it.

**Comment by jpadilla** [comment]
@wbeyda I'd like to know if there's anything specific you don't like, Feel free to open up a PR with a proposal that improves it and we'll review.

Note we're currently using the [mkdocs](http://www.mkdocs.org/user-guide/styling-your-docs/#mkdocs) theme, but we could also use the [readthedocs](http://www.mkdocs.org/user-guide/styling-your-docs/#readthedocs) theme.

**Comment by wbeyda** [comment]
When I made this Issue Bootstrap.css failed to load for some reason and the layout was broke. Seems to be resolved now.

**Comment by jpadilla** [comment]
Probably related to GitHub's downtime yesterday.
