### ISSUE TITLE
How would I go about authenticating with email rather than username? 

### ISSUE THREAD

**Issue by wbeyda** [GetBlimp/django-rest-framework-jwt#339]
How would I go about authenticating with email rather than username?

Is this even possible? Or would I be better off just writing my own view and serializer?

**Comment by brettinternet** [comment]
Set `USERNAME_FIELD = 'email'` inside your User model. More info [here](https://docs.djangoproject.com/en/1.11/topics/auth/customizing/#django.contrib.auth.models.CustomUser.USERNAME_FIELD) on the Django documentation.

**Comment by wbeyda** [comment]
@brettinternet yeah I was trying to avoid making a custom user model. Is there any other way?

**Comment by brettinternet** [comment]
It looks like [Tom Christie recommends](https://stackoverflow.com/questions/778382/accepting-email-address-as-username-in-django) using a custom user model for this. I'm not aware of another way.
