### ISSUE TITLE
request.user returns AnonymousUser

### ISSUE THREAD

**Issue by rob-balfre** [GetBlimp/django-rest-framework-jwt#35]
Is there a method to return the authorised user when using JSONWebTokenAuthentication in DEFAULT_AUTHENTICATION_CLASSES? I'm calling a view very similar to this http://stackoverflow.com/a/20569205 but this doesn't work as request.user returns AnonymousUser.

**Comment by alifarooq96** [comment]
I'm running into the same issue. request.user always returns Anonymous User.
These are my DEFAULT_AUTHENTICATION_CLASSES:

'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ),

**Comment by jubafourali** [comment]
I have the same problem with TokenAuthentication using Postman for tests

'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',

    )

**Comment by alifarooq96** [comment]
I was facing this issue after deploying to AWS EBS. 

You need to allow Authorization headers. Add this to .ebextensions
WSGIPassAuthorization On

**Comment by jubafourali** [comment]
> I was facing this issue after deploying to AWS EBS.
> 
> You need to allow Authorization headers. Add this to .ebextensions
> WSGIPassAuthorization On
Thank's
Where can I find .ebextensions ?
