### ISSUE TITLE
Travis does not run tests on various Python versions

### ISSUE THREAD

**Issue by poxip** [GetBlimp/django-rest-framework-jwt#353]
After going to https://travis-ci.org/GetBlimp/django-rest-framework-jwt/builds/246406709 I noticed that each  build is run under the same Python version (3.5), but the envs specify that tests should be run under Python 2.7, 3.3, 3.4, and 3.5. I know it's a minor bug, but it would be great to make sure that the tests work well under other Python versions than 3.5.

**Comment by jpadilla** [comment]
We run tests using tox so we specify the virtualenv version using the `TOX_ENV` environment variable.
