### ISSUE TITLE
Use JWT token auth for https api failed (return "Authentication credentials were not provided")

### ISSUE THREAD

**Issue by lizeyan** [GetBlimp/django-rest-framework-jwt#354]
When I just deploy this app with apache2 using http, it works fine. But after I set "SSLEngine on" in apache2, I can only access these apis in browser. Accesses via postman or python-requests or curl is all failed with the same error.
![image](https://user-images.githubusercontent.com/12494243/28624379-8e6b9f6a-724b-11e7-9a3a-4b77b673b61d.png)

**Comment by serranoarevalo** [comment]
Isn't the header be 'Authorization' instead of 'Authentication' ?

**Comment by DSTDevOPs** [comment]
Add the following in apache httpd.conf file:
`WSGIPassAuthorization On` 
This worked for me.

**Comment by abijithmg** [comment]
Add the following in apache httpd.conf file:
`WSGIPassAuthorization On`
This worked for me.

**Comment by faridos** [comment]
@abijithmg why we bring that up when none has apache in his setup? 
- for me i have the same issue 
-settings.py :
    REST_FRAMEWORK = {
       'DEFAULT_AUTHENTICATION_CLASSES': (
          'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
      )
  }
- urls.py:
    path(r'api-token-auth/', obtain_jwt_token),
    path(r'api-token-verify/', verify_jwt_token),
![Screenshot from 2019-05-17 19-45-22](https://user-images.githubusercontent.com/3405806/57946532-c97c1000-78dc-11e9-9b70-b6f2609289ec.png)
