### ISSUE TITLE
could i add other information to payload?

### ISSUE THREAD

**Issue by vparenti** [GetBlimp/django-rest-framework-jwt#367]
I would like add more information in payload json, for example 'role' and 'company'.
Is there a way?
Thanks,
V

**Comment by mauzepeda** [comment]
+1

**Comment by Alex3917** [comment]
You just make a custom payload handler, e.g.:

```
from rest_framework_jwt.utils import jwt_payload_handler

def jwt_custom_payload_handler(user):
    payload = jwt_payload_handler(user)
    payload['role'] = 'xyz'
    return payload
```

Then in your settings you just need:

```
JWT_AUTH['JWT_PAYLOAD_HANDLER'] = 'path.to.your.jwt_custom_payload_handler',
```

**Comment by blueyed** [comment]
Could we add this to the docs then?
@vparenti / @mauzepeda a PR would be welcome.

**Comment by mauzepeda** [comment]
@blueyed I've added @Alex3917 example to the docs and made a Pull Request.
