### ISSUE TITLE
Unable to set JWT token in cookies with separate frontend application (React)

### ISSUE THREAD

**Issue by sadan** [GetBlimp/django-rest-framework-jwt#376]
I am trying to set JWT token in cookies. It's working for the django server. But my frontend is written in React. And the value is not being set in the cookies.

```
# in my view

if api_settings.JWT_AUTH_COOKIE:
        expiration = (datetime.utcnow() + api_settings.JWT_EXPIRATION_DELTA)
        response.set_cookie(api_settings.JWT_AUTH_COOKIE,
            response.data['access_token'],
            expires=expiration,
            httponly=True)
```

**Comment by mapeveri** [comment]
Hi, How did you solve this issue?. Thanks!

**Comment by sadan** [comment]
I had to set _withCredentials_ header set to **true** while making requests from frontend.

**Comment by mapeveri** [comment]
Great! Thanks :)
