### ISSUE TITLE
POST 401 (Unauthorized) with Axios

### ISSUE THREAD

**Issue by feedgit** [GetBlimp/django-rest-framework-jwt#390]
I get this error when I use axios to POST data, respond: {"detail":"Authentication credentials were not provided."}. Please help me show the error:
![image](https://user-images.githubusercontent.com/19923843/31595645-6bf0b2fc-b267-11e7-8f5f-757d50513044.png)
![image](https://user-images.githubusercontent.com/19923843/31595648-738de17e-b267-11e7-92b7-65711d0f7c5c.png)
My VUEJS Axios code:
![image](https://user-images.githubusercontent.com/19923843/31595695-b7b2cf22-b267-11e7-9c0d-4d0fd9875f37.png)

Thanks in advance!

**Comment by kitab15** [comment]
Evidently, your Headers were not sent with the request and that is why you receive:

`{"detail":"Authentication credentials were not provided."}`

I recommend using an axiosInstance with common information like baseURL (your API URL) and headers.

```
import axios from 'axios';

const axiosInstance = axios.create({
  baseURL: process.env.REACT_APP_BACKEND_HOST,
  headers: { Authorization: `Bearer ${this.$store.state.token}` },
});

export default axiosInstance;
```
Then, you could call it as follows:

`axiosInstance({ method, url, data, headers })`

**Comment by congtoanle** [comment]
Thank you. It works perfectly.
