### ISSUE TITLE
Unprotected Resource

### ISSUE THREAD

**Issue by Meemaw** [GetBlimp/django-rest-framework-jwt#404]
Hey I want to have unprotected resources like this:

```python
class GroupJoinView(APIView):

    permission_classes = (AllowAny,)

   def get(.....):
       ....
```

This does pass my tests but I get 401 when trying to go to that url form email client.

**Comment by alexanderatallah** [comment]
@Meemaw I'm getting 401s when I add AllowAny to my views. why did you close this?
