### ISSUE TITLE
Does it support Django 2?

### ISSUE THREAD

**Issue by maks-us** [GetBlimp/django-rest-framework-jwt#415]

**Comment by yousifa** [comment]
What is failing under Django 2?

**Comment by maks-us** [comment]
@yousifa 

I have not tested it yet. 
We have no "Django 2" in "Requirements". 
Is it supported? Have somebody tested it already?

```
Requirements
    Python (2.7, 3.3, 3.4, 3.5, 3.6)
    Django (1.8, 1.9, 1.10, 1.11)
    Django REST Framework (3.1, 3.2, 3.3, 3.4, 3.5, 3.6)
```

**Comment by yousifa** [comment]
Yes, it works with Django 2.0. It seems that there have been no official tests, but tested on my system and passes & works properly.

**Comment by gascarcella** [comment]
Tested in Django 2. Works OK with everything except on class based views extending APIView

**Comment by feixiaohuijava** [comment]
yes. I did that in django2 and found no problems. Everything was fine :)
