### ISSUE TITLE
ObtainJSONWebToken endpoint not working for user.is_active = False

### ISSUE THREAD

**Issue by xzibiit** [GetBlimp/django-rest-framework-jwt#428]
when user is not active..endpoint does not shows "User account is disabled"

???????
if all(credentials.values()):
            user = authenticate(**credentials)

            if user:
                if not user.is_active:
                    msg = _('User account is disabled.')
                    raise serializers.ValidationError(msg)

                payload = jwt_payload_handler(user)

                return {
                    'token': jwt_encode_handler(payload),
                    'user': user
                }
            else:
                msg = _('Unable to log in with provided credentials.')
                raise serializers.ValidationError(msg)

**Comment by olicubalibre** [comment]
@xzibiit What does it show? Could you give more info?

**Comment by xzibiit** [comment]
i figured out the problem tx...
