### ISSUE TITLE
No commits since Oct 5, 2017 - Is this project still active?

### ISSUE THREAD

**Issue by rhazegh** [GetBlimp/django-rest-framework-jwt#459]
Is this project still active?

**Comment by 990px** [comment]
@rhazegh Apart from project activity/inactivity try to avoid using JWT as authorization token ;-) https://github.com/shieldfy/API-Security-Checklist/issues/6

**Comment by rhazegh** [comment]
I ended up using knox. https://github.com/James1345/django-rest-knox

No JWT for me ;)
