### ISSUE TITLE
Curious Whether JWT Still Works Given Libraries Requirements Mismatch?

### ISSUE THREAD

**Issue by sgrobert** [GetBlimp/django-rest-framework-jwt#483]
Hi there,

I've been trying to embed the JWT into my codes. The original Django setup was working perfectly up until I found a mismatch of Django Libraries given in the requirements. 

My installed libraries are newer and pip allowed the installations to go through, I would like to enquire if this mismatch will incur errors like having Django throw 500 internal errors, as it is what I am currently experiencing. 

---

**Requirements oif django-rest-framework-jwt:**
```

- Python (2.7, 3.3, 3.4, 3.5, 3.6)
- Django (1.8, 1.9, 1.10, 1.11)
- Django REST Framework (3.1, 3.2, 3.3, 3.4, 3.5, 3.6)

```

**Installed Libraries:**
```

- python==2.7
- Django==1.11.21
- djangorestframework==3.9.4
- djangorestframework-jwt==1.11.0

```

Hope someone can enlighten me if this may be the issue as I have to been trying to identify where is my problem sources given that most of the code are verified to be working copies. 

Thank you!

**Comment by Alex3917** [comment]
I'm using Python 3.6 with the newest versions of Django, Django Rest Framework, and Django Rest Framework JWT. I'm not having any issues. My `requirements.in` file looks like:

```django==2.2.2
djangorestframework==3.9.4
djangorestframework-jwt==1.11.0```

**Comment by jayvdb** [comment]
https://github.com/Styria-Digital/django-rest-framework-jwt is a drop-in replacement fork with Django 2.2 in the travis support matrix.

**Comment by sgrobert** [comment]
Hi @Alex3917  & @jayvdb,

Thanks for replying. I totally forgot to reply and update this conversation.

I have confirmed that any modules that are newer will still work with _django-rest-framework-jwt_ setup. The key point is that there should not be any issue with the versioning of Python, Django, djangorestframework & djangorestframework-jwt.

The primary issue that was eventually resolved, is posted here https://stackoverflow.com/questions/56735323/django-rest-framework-why-adding-isauthenticated-permissions-only-threw-500-int . 

Hope it will potentially help someone else resolve their problem. Cheers!
