### ISSUE TITLE
Access user id and add to session with Ember

### ISSUE THREAD

**Issue by erichaus** [GetBlimp/django-rest-framework-jwt#50]
Hey Jose,

I just saw your message on IRC regarding jwt and including the user ID... I didn't know you also authored the ember simple auth token package which I am also using :) 

I'm new to the ember side of things but have made progress using ember-cli with django. What I want to do is set the user object on the simple auth session. I have actually done this already by creating an initializer, modifying this package on the backend to include the user id with the token and then set it so I can do e.g. {{session.user.email}}

However now that I see you include it by default, Im wondering how/where can I decode that on the frontend and set it in Ember?

Here is my initializer as current:

import Ember from 'ember'
import Session from 'simple-auth/session'

```
# Set the current user on the session.
UserSession = Session.extend
  user: (->
    userId = @get 'id'
    if not Ember.isEmpty userId
      @container.lookup('store:main').find('user', userId)
    ).property 'id'

# Takes two parameters: container and app
initialize = (container, app) ->
  container.register 'session:usersession', UserSession

UserSessionInitializer =
  name: 'user-session'
  before: 'simple-auth'
  initialize: initialize

export default UserSessionInitializer
```

Any help appreciated, thanks and appreciate your work!

PS - I was thinking of maybe extending this package to allow adding arbitrary data to the JWT payload, what do you think?

**Comment by woosungchu** [comment]
I write code in DRF-Ember project too and this discussion help me a lot too.  Almost all of DRF-Ember project beginner may experienced like this invalid signature and jpadilla's kind answer would be very helpful.

**Comment by Assamdiapak** [comment]
from stream_framework.verbs import register
from stream_framework.verbs.base import Verb


class Pin(Verb):
    id = 5
    infinitive = 'pin'
    past_tense = 'pinned'

register(Pin)
.. seealso:: Make sure your verbs are registered before you read data from stream_framework, if you use django
        you can just define/import them in models.py to make sure they are loaded early



Getting verbs
You can retrieve verbs by calling get_verb_by_id.

from stream_framework.verbs import get_verb_by_id

pin_verb = get_verb_by_id(5)

**Comment by Assamdiapak** [comment]
// Get the part of the token where data is stored.
  token = token.split('.')[1];

  // Make URL friendly.
  token = token.replace(/\+/g, '-').replace(/\//g, '_').replace(/\=+$/, '');

  // Reverse to original encoding.
  if (token.length % 4 !== 0) {
    token += ('===').slice(0, 4 - (token.length % 4));
  }

  token = token.replace(/-/g, '+').replace(/_/g, '/');

  // Return the token data decoded.
  return JSON.parse(atob(token));
