### ISSUE TITLE
Generate token manually

### ISSUE THREAD

**Issue by viewlview** [GetBlimp/django-rest-framework-jwt#58]
Is there any way to generate tokens programmatically without sending request?

**Comment by DavidMuller** [comment]
@jpadilla 

Will using 

```python
payload = jwt_payload_handler(user)
token = jwt_encode_handler(payload)
```
skip adding` 'orig_iat'`?  That's something [the `JSONWebTokenSerializer` does](https://github.com/GetBlimp/django-rest-framework-jwt/blob/master/rest_framework_jwt/serializers.py#L55-L66):   

```python
payload = jwt_payload_handler(user)

# Include original issued at time for a brand new token,
# to allow token refresh
if api_settings.JWT_ALLOW_REFRESH:
    payload['orig_iat'] = timegm(
        datetime.utcnow().utctimetuple()
    )

return {
    'token': jwt_encode_handler(payload)
}
```

**Comment by jpadilla** [comment]
@DavidMuller yup, it will skip adding `'orig_iat'`. You'll only need that if you're using token refresh. If you still need it, you can do:

```python
payload = jwt_payload_handler(user)
payload['orig_iat'] = timegm(datetime.utcnow().utctimetuple())
token = jwt_encode_handler(payload)
```

**Comment by jpadilla** [comment]
Closing this, since it's mostly a usage question.

**Comment by mcgeeco** [comment]
Just wondering if you think this might belong in the docs? Or have it's own utility function? I'm using it for automatic login after registration/activation, which I think would be a pretty common use case. Great app!
