### ISSUE TITLE
Is the payload encrypted?

### ISSUE THREAD

**Issue by ajostergaard** [GetBlimp/django-rest-framework-jwt#60]
The doc says: "This is the secret key used to encrypt the JWT." but it looks to me like the JWT is only ever encoded or signed. Have I misunderstood something?

**Comment by jpadilla** [comment]
@ajostergaard good catch, it should probably say sign instead of encrypt.

**Comment by jpadilla** [comment]
Closed via fc40ed685da105010f4b764b7063e60d5dccd6a6
