### ISSUE TITLE
Query token `issue at` 

### ISSUE THREAD

**Issue by samrad** [GetBlimp/django-rest-framework-jwt#66]
Thanks for this useful library. As far as I can tell, you're not using database to store the tokens. May I ask 

 - Where they are stored and how?
 - Is there any way I can include the `iat` in `Response`?

**Comment by jpadilla** [comment]
@samrad tokens are not stored in the backend, that's one of the pros of using JWT for authentication, so they help build a stateless API. A normal workflow might be to store the token in the browser's localstorage or sessionstorage. "Logging out" would just mean removing the token from the client and that's it.

You might want to read a bit more on [authentication with JSON Web Tokens](http://jpadilla.com/search/jwt).

For now, to include anything additional in the response you'll have to implement a custom view yourself.
