### ISSUE TITLE
Encryption of user password in request

### ISSUE THREAD

**Issue by platzhersh** [GetBlimp/django-rest-framework-jwt#67]
Maybe I've missed something, but shouldn't there be a possibility to encrypt or hash the password on the client side before sending it to the REST endpoint? When you don't have a TLS encrypted connection this could add some security.
Of course you would then have to compare the encrypted password directly with the one from the django database.

**Comment by jpadilla** [comment]
@platzhersh you should always have a TLS(HTTPS) encrypted connection when dealing with sensitive information such as login and passwords, be it if your sending them via a POST to an endpoint or submit an HTML form.
