### ISSUE TITLE
Any chance you guys might port this to Falcon/Talons?

### ISSUE THREAD

**Issue by dukedougal** [GetBlimp/django-rest-framework-jwt#69]
Falcon / Talons really needs JWT auth.

https://github.com/racker/falcon
https://github.com/talons/talons

Any chance you guys might consider porting your JWT auth solution to Talons?

**Comment by jpadilla** [comment]
@dukedougal since I don't personally use Falcon or Talons, I'm not in a favorable position to do so. I would instead, advise to anyone interested to go ahead and do it. I'd be available to help out in any other way.
