### ISSUE TITLE
QueryParameterAuthentication

### ISSUE THREAD

**Issue by erichonkanen** [GetBlimp/django-rest-framework-jwt#71]
Hello @jpadilla,

Recently I had to implement an authenticator that received the token via query parameters. Use case is creating a download file button that hits an endpoint e.g. /api/reports/somereport?export=csv

I thought I'd paste it here to see if you would like it added to the lib, maybe others could use it?

```
import jwt

from rest_framework_jwt.settings import api_settings
from rest_framework_jwt.authentication import JSONWebTokenAuthentication


class QueryParameterAuthentication(JSONWebTokenAuthentication):

    def authenticate(self, request):
        """
        Parses the request's Query Parameters for a `token` and sets it
        on the authorization header for authentication.
        """
        if 'token' not in request.QUERY_PARAMS:
            return None

        token = request.QUERY_PARAMS['token']
        header = '{} {}'.format(api_settings.JWT_AUTH_HEADER_PREFIX, token)
        request.META['HTTP_AUTHORIZATION'] = header

        return super(QueryParameterAuthentication, self).authenticate(request)
```

**Comment by jpadilla** [comment]
@erichonkanen real nice workaround. Let's leave this around for a few days to see if anyone else is interested. Seems simple and useful enough to include.

**Comment by jpadilla** [comment]
@erichonkanen you might be interested in #80
