### ISSUE TITLE
Token verification view

### ISSUE THREAD

**Issue by Jwpe** [GetBlimp/django-rest-framework-jwt#74]
We are thinking of using this library to create an authentication microservice in a cluster of server-side applications.The current implementation is great for when your protected resources are on the same server as your JWT endpoint, but would need some alteration for if these were on separate apps.

The authentication flow I am considering is as follows:  a user would log on from our client-side single page app by hitting an endpoint on the auth microservice (AuthService) that serves the `obtain_jwt_token` view. They would then store their JWT in-browser. If the client-side application needed to request a resource from another server-side application (ResourceService), it would pass the JWT in the header. However, the idea is that ResourceService would not have to verify the authenticity of the JWT itself - rather it would make a secondary HTTP call to AuthService to check if the JWT was valid.

This would mean setting up a second type of view on the AuthService which received a JWT and verified its authenticity. I don't think this would be difficult to do by abstracting out most of the `authenticate` method of the `JSONWebTokenAuthentication` class to give it the flexibility to be used either as a function in a view or as a REST framework authentication class.

I wondered if you think a view like this would be a useful addition to the library, or if it is outside the scope of what you are wanting to achieve?

**Comment by jpadilla** [comment]
@Jwpe thanks for bringing this up. I think it's a totally valid discussion worth having with all these new discussions on SOA and microservices.

Your approach makes sense to me, but I'd also look into actually sharing the `JWT_SECRET_KEY` with all your services and actually verifying tokens within each service since that's pretty "cheap" and easy to do(no db calls needed to verify and decode the token). Your token can contain any information you'd need like the user's id. This would save you those extra requests.

Thoughts?

**Comment by Jwpe** [comment]
@jpadilla I agree it's definitely a possibility to take the approach of having the secret key present on all services, and authenticating requests in place. 

The main reason that I was going for the 'single point of authentication' approach was to separate that concern from all of the other services. It would be fine if all of our services were guaranteed to be serving their API using Django/DRF - however this isn't a constraint we want to introduce. For example, if one of my services is a Node application, I would have to reimplement the token verification in JavaScript if I wanted to do authentication within the service. Alternatively, I could just make a request to the AuthService, which would be super easy to implement. 

I think both approaches are valid and I would definitely choose your suggested route for high request volume apps. It could be that the other approach isn't something worth supporting directly - I'm sure I can find a workaround.

Thanks for the quick feedback and for making a very useful library!

**Comment by jpadilla** [comment]
@Jwpe the actual token verifying and decoding part isn't specific to what we're doing here, check out http://jwt.io/ for existing libraries.

If you are going with your original idea, this endpoint would just verify the JWT and perhaps return it's decoded content?

**Comment by Jwpe** [comment]
@jpadilla I made a PR, since I thought that would be the clearest way to explain it! #75 

I figured out that most of the logic was already present in the refresh endpoint. Currently the verification endpoint returns exactly the same response as the refresh endpoint, only without refreshing the token. However, it shares functionality so you could use your `jwt_response_payload_handler` to get it to return whatever you wanted, e.g. the decoded content.

**Comment by jpadilla** [comment]
@Jwpe Released v1.3.0 with this. Thanks again!
