### ISSUE TITLE
Documentation around Existing Session

### ISSUE THREAD

**Issue by cancan101** [GetBlimp/django-rest-framework-jwt#78]
The docs show keeping the existing auth mechanisms:
```
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
....
```
but I assume that if I want to use only jwt I can remove those two? If I do remove `SessionAuthentication`, I assume that I can then remove `django.contrib.sessions.middleware.SessionMiddleware` and `django.contrib.auth.middleware.SessionAuthenticationMiddleware` from the `MIDDLEWARE_CLASSES`? (per: [this note](https://docs.djangoproject.com/en/1.7/topics/http/sessions/#enabling-sessions))

Might be worth tossing a note in the docs about this.

**Comment by jpadilla** [comment]
Sure thing, you can remove those. Regarding, actually removing any other session related middleware or apps from your settings, depends if you're not gonna be using the admin, since that requires sessions to be working.
