### ISSUE TITLE
Notes on  RSASSA-PKCS1-v1_5 Should be Updates

### ISSUE THREAD

**Issue by cancan101** [GetBlimp/django-rest-framework-jwt#82]
>For the RSASSA-PKCS1-v1_5 algorithms, the "secret" argument in jwt.encode is supposed to be a private RSA key as imported with Crypto.PublicKey.RSA.importKey. Likewise, the "secret" argument in jwt.decode is supposed to be the public RSA key imported with the same method.

1. It isn't clear what library has `Crypto.PublicKey.RSA.importKey`
2. Probably want to use `cryptography` anyways
3. `pyjwt` handles strings now in some cases so no special action is needed,

**Comment by jpadilla** [comment]
Good point, I'm going to update that section of the docs and point towards `PyJWT`.
