### ISSUE TITLE
 customize djangorestframework-jwt for authentication with email or username interchangeably  and password                              

### ISSUE THREAD

**Issue by xmonfort** [GetBlimp/django-rest-framework-jwt#84]
I am writing a backend api using django rest-framework. I would like jwt authentication using email or username interchangeably   (one or other) and password instead of using username and password. 
Is there any way using your djangorestframework-jwt package?

Thanks in advance.

Xavier Monfort Faure

**Comment by jpadilla** [comment]
@xmonfort There are a couple of ways, you could write your own serializer based off `JSONWebTokenSerializer`. It currently uses your User's model `USERNAME_FIELD`, which by default is `username`. It uses your authentication backend to authenticate your user based on that field and `password`. You could use the default serializer implementation and probably just have a a custom authentication backend that checks if the username looks like an email and try to find a user that way.

**Comment by titusjoyson** [comment]
I need to add an additional field in JSONWebTokenSerializer so i can use it in authenticate() function, but i don't know how to extend and implement it, is there any reference to do it.

**Comment by elflamo** [comment]
https://stackoverflow.com/questions/34332074/django-rest-jwt-login-using-username-or-email/46191939#46191939
