### ISSUE TITLE
test.py

### ISSUE THREAD

**Issue by gurinov** [GetBlimp/django-rest-framework-jwt#85]
Hello!
Is the file "rest_framework_jwt/test.py" should not be included for easy import "APIJWTTestCase"  module?

**Comment by jpadilla** [comment]
@gurinov yeap it should be. I'll try to release a new version with it before next week.

**Comment by gurinov** [comment]
Thanks u!

**Comment by jpadilla** [comment]
Released v1.3.0 with this.
