### ISSUE TITLE
No packaged file at version 1.3.0

### ISSUE THREAD

**Issue by monovertex** [GetBlimp/django-rest-framework-jwt#86]
When I try to download the latest version using pip, I receive the following error:

`Could not find a version that satisfies the requirement djangorestframework-jwt==1.3.0 (from -r requirements.txt (line 8)) (from versions: 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 1.0.1, 1.0.2, 1.1.0, 1.1.1, 1.2.0, 0.1.6, 1.0.0, 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 1.0.0, 1.0.1, 1.0.2, 1.1.0, 1.1.1, 1.2.0)`

A simple Google search gives me [this question on SO](http://stackoverflow.com/questions/4620459/pip-cant-find-latest-versions-of-a-pypi-project).

Can you please properly package this version so I can install it using pip?

**Comment by jpadilla** [comment]
@monovertex sorry about that something went wrong when publishing last version, just bumped the version to 1.3.1 and published. Check it out and let me know if that works well. Thanks!
