### ISSUE TITLE
Allow token invalidation

### ISSUE THREAD

**Issue by erichonkanen** [GetBlimp/django-rest-framework-jwt#87]
Hello @jpadilla,

I was having discussion with another dev and thinking about the ember jwt app and the potential to add an enhancement that allows activity based token expiration.

At a high level the frontend would authenticate as usual but begin a countdown timer after last activity of user. If the countdown got to 0 it would issue an api request to invalidate the token on the backend and log them out on the frontend.

Just wanted to see what your thoughts are on this? Is it a logical use case? I know i've seen sites (banking etc) that log you out after inactivity....

-E

**Comment by erichonkanen** [comment]
Hm after thinking about this some more maybe its not as straightforward as I was thinking... It seems like there is no obvious way to invalidate a jwt token? I found [this](http://stackoverflow.com/questions/21978658/invalidating-json-web-tokens) SO link that touches on it.

**Comment by jpadilla** [comment]
@erichonkanen shouldn't your first option here be short expire times?

**Comment by erichonkanen** [comment]
That depends.. if you don't mind having large numbers of token refresh requests then sure that would work for ensuring that a logged out client's key would be invalidated within a short time. If you didn't want to use such short expire times there is still an issue that it doesn't seem there is any straightforward way to invalidate a single jwt token.

Not sure if an activity-based model would work with jwt

**Comment by erichonkanen** [comment]
closing as unsure of use case and ability to invalidate a jwt token
