### ISSUE TITLE
Allow JWT_AUDIENCE to be a list of Strings

### ISSUE THREAD

**Issue by cancan101** [GetBlimp/django-rest-framework-jwt#96]
Right now, per [the docs](https://github.com/GetBlimp/django-rest-framework-jwt/blob/96eb5d9838967a88dfc7d92acfd21ba7481bf50b/docs/index.md#jwt_audience):
> This is a string that will be checked against the `aud`...

I would suggest allowing for a list of valid `aud` values.

**Comment by jpadilla** [comment]
@cancan101 I think it should actually work well if you do use a list of `aud` values, since we just pass that along to PyJWT. Did you try that?

**Comment by cancan101** [comment]
I think that won't work: https://github.com/jpadilla/pyjwt/blob/78742f7bee089757839921d76604b6d24d6adc32/jwt/api.py#L144

**Comment by jpadilla** [comment]
@mark-adams should this be a possibility on `PyJWT`?

**Comment by mark-adams** [comment]
The JWT can have a list of audiences or a single string in the aud claim but the application can only specify a single audience in the `jwt.decode(token, audience=aud)` parameter.

This is in line with the spec which says
> Each principal intended to process the JWT MUST identify itself with a value in the audience claim.

The key distinction here being *a value*; not *one or more values*. This is consistent with the Ruby library as well.
