### ISSUE TITLE
OperationalError: no such table: auth_user

### ISSUE THREAD

**Issue by caot** [GetBlimp/django-rest-framework-jwt#97]
cloned the project, and run the test as the following with the following error. Can anyone shed some ligh on the issue?

$ ./runtests.py
==================================================================================================================================== test session starts =====================================================================================================================================
platform linux2 -- Python 2.7.2 -- py-1.4.26 -- pytest-2.6.4
collected 43 items 

tests/test_authentication.py FFFFFFFFFFss
tests/test_serializers.py FFsFFF
tests/test_utils.py FFFFFFFFFF
tests/test_views.py FFFFFFFFFFFFFFF

========================================================================================================================================== FAILURES ==========================================================================================================================================
_____________________________________________________________________________________________________________ JSONWebTokenAuthenticationTests.test_different_auth_header_prefix ______________________________________________________________________________________________________________

self = <tests.test_authentication.JSONWebTokenAuthenticationTests testMethod=test_different_auth_header_prefix>

    def setUp(self):
        self.csrf_client = APIClient(enforce_csrf_checks=True)
        self.username = 'jpueblo'
        self.email = 'jpueblo@example.com'
>       self.user = User.objects.create_user(self.username, self.email)

tests/test_authentication.py:79: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../apps/python-2.7.2/lib/python2.7/site-packages/django/contrib/auth/models.py:187: in create_user
    **extra_fields)
../../apps/python-2.7.2/lib/python2.7/site-packages/django/contrib/auth/models.py:182: in _create_user
    user.save(using=self._db)
../../apps/python-2.7.2/lib/python2.7/site-packages/django/db/models/base.py:710: in save
    force_update=force_update, update_fields=update_fields)
../../apps/python-2.7.2/lib/python2.7/site-packages/django/db/models/base.py:738: in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
../../apps/python-2.7.2/lib/python2.7/site-packages/django/db/models/base.py:822: in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
../../apps/python-2.7.2/lib/python2.7/site-packages/django/db/models/base.py:861: in _do_insert
    using=using, raw=raw)
../../apps/python-2.7.2/lib/python2.7/site-packages/django/db/models/manager.py:127: in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
../../apps/python-2.7.2/lib/python2.7/site-packages/django/db/models/query.py:920: in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
../../apps/python-2.7.2/lib/python2.7/site-packages/django/db/models/sql/compiler.py:963: in execute_sql
    cursor.execute(sql, params)
../../apps/python-2.7.2/lib/python2.7/site-packages/django/db/backends/utils.py:64: in execute
    return self.cursor.execute(sql, params)
../../apps/python-2.7.2/lib/python2.7/site-packages/django/db/utils.py:97: in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
../../apps/python-2.7.2/lib/python2.7/site-packages/django/db/backends/utils.py:64: in execute
    return self.cursor.execute(sql, params)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <django.db.backends.sqlite3.base.SQLiteCursorWrapper object at 0x2321510>, query = 'INSERT INTO "auth_user" ("password", "last_login", "is_superuser", "username", "first_name", "last_name", "email", "is_staff", "is_active", "date_joined") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'
params = ['!PFhnSZujHPvSBGh0Fi0a5cmMhZKvPzYfu3f4gzJO', None, False, 'jpueblo', '', '', ...]

    def execute(self, query, params=None):
        if params is None:
            return Database.Cursor.execute(self, query)
        query = self.convert_query(query)
>       return Database.Cursor.execute(self, query, params)
E       OperationalError: no such table: auth_user

**Comment by jpadilla** [comment]
@caot that's weird, not really sure what might be going on there. Maybe you have a `DJANGO_CONFIGURATION` env var set from another project or something like that.
