### ISSUE TITLE
JWT_ALLOW_REFRESH working?

### ISSUE THREAD

**Issue by aRkadeFR** [GetBlimp/django-rest-framework-jwt#98]
hello,
I try to enable the refresh feature for the JWT auth.
I set the settings JWT_ALLOW_REFRESH to True, so as the documentation said:
```
Enable token refresh functionality. Token issued from rest_framework_jwt.views.obtain_jwt_token will have an orig_iat field
```
I should have a orig_iat field in my response in the obtain_jwt_token, but I dont.

Looking at the code, the payload is well overrided with orig_iat in file serializers.py at line 69, but then completely missing from the following lines while encoding the token.

Am I missing something? Should I override the jwt_encode_handler?

Thanks

**Comment by jpadilla** [comment]
The `orig_iat` in line 69 is currently being added to the payload that is then encoded, so the `orig_iat` is in the JWT not in the actual response.

**Comment by aRkadeFR** [comment]
True, I noticed that later... And the refresh is working perfectly like the documentation states :)
Thanks

**Comment by mariowise** [comment]
I don't understand how to retrieve the orig_iat from the JWT. I'm testing the token with http://jwt.io/ and it gives me invalid signature on all tokens, I can't see the orig_iat :S
